README.md
mobile-client-service.template.yaml

Add a client for the mobile client service along with information on how to use it.

AEROGEAR-7680 Add template for mobile client service

---

.circleci/config.yml
makefile

Try to fix build on master branch.

 💚 Run builds in separate containers

---

ui/src/components/BuildConfig.js
ui/src/components/BuildConfig.scss
ui/src/components/ComponentLabel.js
ui/src/components/ComponentLabel.scss

https://issues.jboss.org/browse/AEROGEAR-7709

Create the build config component

---

ui/.gitignore
ui/package-lock.json
ui/package.json
ui/src/components/Client.js
ui/src/components/ConfigurationView.js
ui/src/components/ConfigurationView.scss
ui/src/components/CopyToClipboardMultiline.js
ui/src/components/CopyToClipboardMultiline.scss
ui/src/components/Header.js
ui/src/components/Header.scss
ui/src/components/InlineEdit.js
ui/src/components/InlineEdit.scss
ui/src/components/ServiceSDKInfo.js
ui/src/components/ServiceSDKInfo.scss
ui/src/index.js
ui/src/style/index.scss

https://issues.jboss.org/browse/AEROGEAR-7666

Create the mobile configuration view

---

ui/package-lock.json
ui/package.json
ui/src/components/build/MobileClientBuildHistoryList.js
ui/src/components/build/MobileClientBuildHistoryList.scss
ui/src/components/overview/MobileClientListViewItem.js
ui/src/components/overview/OverviewListItem.scss

https://issues.jboss.org/browse/AEROGEAR-7712

Create build history component

---

README.md

Update README with CRD setup

---

ui/src/DataService.js
ui/src/components/Client.js

@sedroche adding the extra option fixed the problem for me.

 🐛 make sure the cookies are sent to the backend when using fetch

---

ui/src/components/build/CreateClientBuild.js
ui/src/components/build/CreateClientBuild.scss
ui/src/components/build/NoBuild.js
ui/src/components/build/NoBuild.scss
ui/src/components/build/NoBuildConfig.js
ui/src/components/build/NoBuildConfig.scss
ui/src/components/common/FormDropdown.js
ui/src/components/common/FormDropdown.scss
ui/src/components/common/KeyValueEditor.js
ui/src/components/common/KeyValueEditor.scss

https://issues.jboss.org/browse/AEROGEAR-7734
https://issues.jboss.org/browse/AEROGEAR-7735
https://issues.jboss.org/browse/AEROGEAR-7736

Aerogear 7734

---

ui/.eslintrc.json
ui/package-lock.json
ui/package.json

* https://github.com/aerogear/mobile-client-service/network/dependencies
* Eslint error: `[eslint] 'fetch' is not defined. (no-undef)`

fix: vulneratilities, eslint 'fetch' error

---

ui/src/DataService.js
ui/src/actions/apps.js
ui/src/actions/builds.js
ui/src/components/build/MobileClientBuildListItem.js
ui/src/components/build/MobileClientBuildsList.js
ui/src/components/build/NoBuild.js
ui/src/components/overview/MobileClientOverviewList.js
ui/src/containers/Client.js
ui/src/containers/CreateClient.js
ui/src/containers/Overview.js
ui/src/containers/StartBuildButton.js
ui/src/reducers/builds.js

https://issues.jboss.org/browse/AEROGEAR-7922
1. deploy local OpenShift with mobile-core
2. provision mobile CI/CD service
3. create mobile client
4. open mobile client's details and navigate to builds tab
5. create new build configuration (you can use https://github.com/aerogear/cordova-showcase-template.git)
6. fetch and checkout this PR
7. `make serve`
8. open `localhost:4000` in your browser
9. open the mobile app and navigate to builds tab
10. expand build config
11. click on start build button
12. new build should start

Triggering builds with UI

---

ui/package-lock.json
ui/package.json
ui/src/components/build/BuildPipelineStage.js
ui/src/components/build/BuildPipelineStage.scss
ui/src/components/build/MobileClientBuildListItem.js

https://issues.jboss.org/browse/AEROGEAR-7946
1. deploy local OpenShift with mobile-core
2. provision mobile CI/CD service
3. create mobile client
4. open mobile client's details and navigate to builds tab
5. create new build configuration (you can use https://github.com/aerogear/cordova-showcase-template.git)
6. fetch and checkout this PR
7. `make serve`
8. in OpenShift console start new build
9. open `localhost:4000` in your browser
10. open the mobile app and navigate to builds tab
11. expand build config
12. you should see progress bars showing stages of the build
13. refresh page to watch build progress

Added progress bars for builds

---

ui/src/DataService.js
ui/src/actions/buildConfigs.js
ui/src/components/build/MobileClientBuildListItem.js
ui/src/containers/DeleteBuildButton.js
ui/src/reducers/buildConfigs.js
ui/src/reducers/resource.js

https://issues.jboss.org/browse/AEROGEAR-7923
1. Make sure the OpenShift project you are targeting has Mobile CI/CD provisioned
1. Create Mobile Client and couple of buildconfigs in your OpenShift project
1. Refresh MDC UI
1. Select your Client -> Builds and try to delete them
1. Verify builds have been removed (also check in OpenShift UI) and that there are no errors in developer console
* based on https://github.com/aerogear/mobile-client-service/pull/58

UI: deleting buildConfigs

---

ui/src/components/build/BuildSummary.js
ui/src/components/build/MobileClientBuildHistoryList.js

https://issues.jboss.org/browse/AEROGEAR-7959
💁‍♂️  Feel free to use [my project on community cluster](https://community.skunkhenry.com/console/project/psturc-test/overview) (ping me for user/pass if you don't have it)
1. Make sure the OpenShift project you are targeting has Mobile CI/CD provisioned
1. Create Mobile Client and couple of buildconfigs in your OpenShift project
1. Trigger build (couple of times) and wait until at least first stage is started for every build (otherwise [you'll see the error](https://github.com/aerogear/mobile-client-service/pull/62#pullrequestreview-159164458))
1. Refresh MDC UI
1. Select your Client -> Builds and …

Links to Jenkins build logs

---

ui/src/components/mobileservices/BoundServiceRow.js
ui/src/components/mobileservices/MobileServiceView.js
ui/src/components/mobileservices/UnboundServiceRow.js
ui/src/components/overview/MobileClientOverviewList.js

https://issues.jboss.org/browse/AEROGEAR-7965
💁‍♂️  Feel free to use [my project on community cluster](https://community.skunkhenry.com/console/project/psturc-test/overview) (ping me for user/pass if you don't have it)
1. Make sure the OpenShift project you are targeting has Mobile CI/CD provisioned
1. Create Mobile Client and couple of buildconfigs in your OpenShift project
1. Refresh MDC UI
1. Open browser developer console and just do a "click tour" through the app
1. Verify there are no errors present in the console

Fix errors in browser developer console

---

cmd/api-server/main.go
pkg/mobile/build.go
pkg/mobile/build_test.go
pkg/mobile/interfaces.go
pkg/web/buildsHandler.go
pkg/web/buildsHandler_test.go

@wei-lee these changes should address comments in Pavel's PR [1]. Can you have a look?
[1] https://github.com/aerogear/mobile-developer-console/pull/70

Fixes - addressing comments

---

.realize.yaml
ui/.eslintrc.json
ui/package-lock.json
ui/package.json
ui/src/style/_variables.scss

Replaced `airbnb` rules with `patternfly-react` rules (based on `standard`). Also applied auto-fix.
This PR replaces https://github.com/aerogear/mobile-client-service/pull/61.

Eslint patternfly-react rules

---

scripts/development.sh
ui/src/components/create_client/BaseCreateMobileClient.js
ui/src/components/create_client/CreateClientFormUtils.js
ui/src/containers/CreateClient.js

https://issues.jboss.org/browse/AEROGEAR-7987
Fixed warnings and minor issue with progress not being reset when closing and reopening creation dialog. Also fix in `development` script - remove log before printing it's output.
We should get rid of warnings.
Warning about props being passed to state was resolved by changing the way of passing the props and updating state on props change. The other error was caused by not setting initial value for inputs.

Fixed warnings when creating Application

---

pkg/web/mobileClientsHandler.go
ui/src/DataService.js

https://issues.jboss.org/browse/AEROGEAR-7981

Return error message for failed app creation

---

ui/src/components/App.js
ui/src/components/App.scss
ui/src/components/common/NavHeader.js
ui/src/components/overview/MobileClientCardView.js
ui/src/components/overview/MobileClientCardView.scss
ui/src/components/overview/MobileClientCardViewItem.js
ui/src/containers/Client.js
ui/src/containers/CreateClient.js
ui/src/containers/Overview.js

Styling fixes

---

ui/src/components/overview/MobileClientCardView.js

https://issues.jboss.org/browse/AEROGEAR-7994
Filtering now works for apps
It's cool and handy to have it
Checking the names of apps against the filter in state
💁‍♂️  Feel free to use [my project on community cluster](https://community.skunkhenry.com/console/project/psturc-test/overview) (ping me for user/pass if you don't have it)
1. In MDC, go to main page (`/overview`), create a bunch of apps, and try out the filter

Completed filtering of apps

---

ui/src/components/App.scss
ui/src/components/overview/MobileClientCardView.js
ui/src/components/overview/MobileClientCardView.scss

Client page did not fill full height of browser window - wrong background color for rest of page with no content.
Fixed css styling
the grey part

Fix - page full height

---

ui/src/components/overview/MobileClientCardView.js
ui/src/components/overview/MobileClientCardViewItem.js
ui/src/containers/Client.js
ui/src/containers/Overview.js

https://issues.jboss.org/browse/AEROGEAR-7996
Removed the mock builds data in the card view
1. Create few apps with few build configs
2. Verify that there is no build info in the app cards
3. Start some builds, make some of them fail by providing wrong git source url (to the build config)
4. Verify build statuses

Remove the mock builds data in the card view

---

ui/src/components/common/NavHeader.js
ui/src/containers/Header.js

https://issues.jboss.org/browse/AEROGEAR-7998

Link to documentation in navbar

---

ui/package-lock.json
ui/src/components/common/NavHeader.js
ui/src/components/common/NavHeader.scss

https://issues.jboss.org/browse/AEROGEAR-8000
Added navbar title.
Bug in patternfly-react `Masthead` component.
https://github.com/patternfly/patternfly-react/issues/757
Replaced `Masthead` component with `div` elements.
PR created to fix this issue - https://github.com/patternfly/patternfly-react/pull/758

Added navbar title

---

README.md
mobile-developer-console.template.yaml
scripts/mdc-oc-cluster-up.sh

https://issues.jboss.org/browse/AEROGEAR-8003
* updated readme
* created another script for setting up `oc cluster up` for local development
* updated template for quick setup of MDC
Previously a readme was a bit confusing for some people
With keyboard
1. Follow the steps for the [oc cluster up part](https://github.com/aerogear/mobile-developer-console/blob/9981f01a1286f503c816cfee0dec812faef2e204/README.md#oc-cluster-up)
1. Verify you can start with development by following the steps [here](https://github.com/aerogear/mobile-developer-console/blob/9981f01a1286f503c816cfee0dec812faef2e204/README.md#run-locally)

Readme update

---

ui/package-lock.json
ui/src/DataService.js
ui/src/actions/users.js
ui/src/components/common/NavHeader.js
ui/src/containers/Header.js
ui/src/reducers/user.js

https://issues.jboss.org/browse/AEROGEAR-7993
Implement the logout function
need to allow users to logout
Redirect user to the "/oauth/sign_in" page. It will clear the session cookie and return the login view.
1. Login to https://mdc-server-psturc-test.community.skunkhenry.com
2. Perform logout after logged in.
3. Check the session cookie is gone.

 ✨ implement the logout function

---

ui/src/components/overview/MobileClientCardViewItem.js

Fixed services styling in app card

---

.circleci/config.yml
Makefile
ui/package-lock.json
ui/package.json
ui/src/components/common/BuildStatus.test.js
ui/src/components/common/ComponentSectionLabel.test.js
ui/src/components/common/CopyToClipboardMultiline.test.js
ui/src/components/common/FormDropdown.test.js
ui/src/components/common/KeyValueEditor.js
ui/src/components/common/KeyValueEditor.test.js
ui/src/components/common/MobileClientConfig.test.js
ui/src/components/common/MobileListViewItem.test.js
ui/src/components/common/NavHeader.test.js
ui/src/components/common/PlatformIcon.test.js

https://issues.jboss.org/browse/AEROGEAR-8013
Add some unit tests for the UI

 ✅ add unit tests for UI

---

ui/package-lock.json
ui/package.json
ui/src/components/configuration/Header.test.js
ui/src/components/overview/MobileClientCardView.test.js
ui/src/components/overview/MobileClientCardViewItem.test.js
ui/src/containers/Overview.js
ui/src/containers/Overview.test.js

Aerogear 8013 ui tests

---

pkg/web/buildConfigsHandler.go
pkg/web/buildConfigsHandler_test.go
pkg/web/buildsHandler.go
pkg/web/mobileClientsHandler.go
pkg/web/mobileClientsHandler_test.go
pkg/web/serverConfigHandler.go
pkg/web/serviceInstancesHandler.go
ui/package-lock.json
ui/src/DataService.js
ui/src/actions/errors.js
ui/src/components/App.js
ui/src/containers/Client.js
ui/src/containers/ErrorMessages.js
ui/src/containers/ErrorMessages.test.js
ui/src/reducers/resource.js

https://issues.jboss.org/browse/AEROGEAR-8047
https://issues.jboss.org/browse/AEROGEAR-7964
Verify that there are correct error messages shown in UI.
1. `./scripts/development.sh`
2. Try to create app with name that already exist
3. Open url for app name that does not exist
4. Try to kill backend with `lsof -i tcp:4000 | grep LISTEN | awk '{print $2}' | xargs kill`
5. restart MDC
6. `oc logout`

Error notifications

---

.gitignore
README.md
scripts/minishift.sh
scripts/oc-cluster-up.sh
scripts/post_install.sh
scripts/setup-router-certs.sh
scripts/yml/aerogearcatalog_registry.yaml
scripts/yml/update_instructions.yaml

https://issues.jboss.org/browse/AEROGEAR-8060
Docs for OpenShift 3.11 configuration
Script for configuring mobile services
3.11 support was missing in mobile-core isntaller
Will be added

Instructions + script for OpenShift 3.11

---

pkg/web/mobileClientsHandler.go
pkg/web/mobileClientsHandler_test.go
pkg/web/types.go
ui/src/DataService.js
ui/src/actions/apps.js
ui/src/components/create_client/CreateAndroidClient.js
ui/src/components/create_client/CreateCordovaClient.js
ui/src/components/create_client/CreateIOSClient.js
ui/src/components/create_client/CreateMobileClientBaseClass.js
ui/src/components/create_client/CreateXamarinClient.js
ui/src/components/create_client/EditMobileClientBaseClass.js
ui/src/components/create_client/EditMobileClientBaseClass.test.js
ui/src/components/overview/MobileClientCardViewItem.js
ui/src/containers/Client.js
ui/src/containers/ClientEditBaseClass.js
ui/src/containers/CreateClient.js
ui/src/containers/DeleteItemButton.js
ui/src/containers/EditItemButton.js
ui/src/reducers/apps.js
ui/src/reducers/resource.js

https://issues.jboss.org/browse/AEROGEAR-8015
- Changed the `update` endpoint so that updating the `appName` is supported
- Added a new `update` method to the DataService class
- Added a new `update app` reducer
- Changed MobileCardView to visualize `spec.name` instead of `metadata.name`
- Changed BreadCrump to display `spec.name` instead of `metadata.name`
- Changed DeleteItemButton to display `spec.name` instead of `metadata.name`
- Added EditItemButton

AEROGEAR-8015 - Add app edit function

---

ui/src/components/mobileservices/UnboundServiceRow.js

See https://issues.jboss.org/browse/AEROGEAR-8084

Relabelling button

---

cmd/api-server/main.go
pkg/web/mobileClientsHandler.go
pkg/web/mobileClientsHandler_test.go
ui/src/components/configuration/ConfigurationView.js

https://issues.jboss.org/browse/AEROGEAR-8033
Remove mock data for mobile-services.json. Update clusterName, namespace and clientID with real data.

Load mobile client config to the UI

---

.gitignore
README.md
integration_tests/mobile_clients/index.js
integration_tests/package-lock.json
integration_tests/package.json
integration_tests/runner.test.js
integration_tests/util/sendRequest.js

https://issues.jboss.org/browse/AEROGEAR-8012
Follow [these instructions](https://github.com/aerogear/mobile-developer-console/compare/master...AEROGEAR-8012?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8R156)

feat: integration tests

---

deploy/cr.yaml
deploy/crd.yaml
integration_tests/mobile_clients/index.js
pkg/apis/aerogear/v1alpha1/types.go
pkg/web/mobileClientsHandler.go
pkg/web/mobileClientsHandler_test.go
pkg/web/types.go
ui/package-lock.json
ui/src/components/create_client/Constants.js
ui/src/components/create_client/CreateClient.js
ui/src/components/create_client/EditMobileClientBaseClass.js
ui/src/components/create_client/EditMobileClientBaseClass.test.js
ui/src/components/overview/MobileClientCardView.js
ui/src/containers/Client.js
ui/src/containers/ClientEditBaseClass.js
ui/src/models/mobileapps/mobileapp.js
ui/src/models/mobileapps/mobileappspec.js

https://issues.jboss.org/browse/AEROGEAR-8100
* Removed app identifier in backend and in frontend

AEROGEAR-8100 - App identifier no more

---

pkg/mobile/bindableServices_test.go
pkg/mobile/mockBindableServices.go
pkg/mobile/mockMobileClient.go
pkg/mobile/secrets_test.go
pkg/stub/secretsChangeHandler_test.go
pkg/web/serviceBindingsHandler_test.go

https://issues.jboss.org/browse/AEROGEAR-8092
Add some tests for the backend implementation of servicebindings
Make sure the CI passes

add tests for bindableservice

---

ui/package.json
ui/src/components/bindingUtils.js
ui/src/components/bindingUtils.test.js
ui/src/components/common/BuildStatus.test.js
ui/src/components/common/ComponentSectionLabel.test.js
ui/src/components/common/CopyToClipboardMultiline.test.js
ui/src/components/common/FormDropdown.test.js
ui/src/components/common/KeyValueEditor.test.js
ui/src/components/common/MobileClientConfig.test.js
ui/src/components/common/MobileListViewItem.test.js
ui/src/components/common/NavHeader.test.js
ui/src/components/configuration/Header.test.js
ui/src/components/create_client/EditMobileClientBaseClass.test.js
ui/src/components/mobileservices/BindingPanel.js
ui/src/components/mobileservices/BindingPanel.test.js
ui/src/components/mobileservices/BoundServiceRow.js
ui/src/components/mobileservices/BoundServiceRow.test.js
ui/src/components/mobileservices/bindingPanelUtils.js
ui/src/components/mobileservices/bindingPanelUtils.test.js
ui/src/components/overview/MobileClientCardView.test.js
ui/src/components/overview/MobileClientCardViewItem.test.js
ui/src/containers/Client.test.js
ui/src/containers/ErrorMessages.test.js
ui/src/containers/Overview.test.js
ui/src/setupTests.js

https://issues.jboss.org/browse/AEROGEAR-8092
UI tests
We want higher coverage score!
Using Enzyme & Jest
* fixed [ui/src/components/bindingUtils.js](https://github.com/aerogear/mobile-developer-console/compare/AEROGEAR-8092?expand=1#diff-cb613a5c1650121048c73c94653e346d)
* fixed [ui/src/components/mobileservices/BoundServiceRow.js](https://github.com/aerogear/mobile-developer-console/compare/AEROGEAR-8092?expand=1#diff-af091a3b33dec60711e7fe0e906949f7)

UI tests (binding)

---

Gopkg.lock
pkg/mobile/bindableServices.go
pkg/mobile/bindableServices_test.go
pkg/mobile/interfaces.go
pkg/mobile/mockBindableServices.go
pkg/web/router.go
pkg/web/serviceBindingsHandler.go
ui/package-lock.json
ui/src/DataService.js
ui/src/components/mobileservices/BoundServiceRow.js
ui/src/components/mobileservices/MobileServiceView.js

https://issues.jboss.org/browse/AEROGEAR-8088
This adds much more dynamic behaviors to the service binding screen and fixes a few weird bugs.
1. Create a binding, watch it update
2. Delete a binding watch it update.

Aerogear 8088 live bindings

---

pkg/stub/secretsChangeHandler.go
pkg/stub/secretsChangeHandler_test.go

https://issues.jboss.org/browse/AEROGEAR-8130
1. Run the MDC in this PR
2. Deploy any of the services or all of them: push, metrics, sync, keycloak
3. Create an app and bind the app to any or all the available services
4. After the binding is completed, check mobile-services.json file and it should updated.

 🎨 do not rely on the "id" field in the secret

---

ui/src/components/mobileservices/MobileServiceView.js

Similarly as in https://github.com/aerogear/mobile-developer-console/blob/master/ui/src/containers/Client.js#L66

fix: closing wsServices

---

cmd/api-server/main.go
pkg/mobile/appDeleter.go
pkg/mobile/appDeleter_test.go
pkg/mobile/bindableServices.go
pkg/mobile/bindableServices_test.go
pkg/mobile/buildConfig.go
pkg/mobile/buildConfig_test.go
pkg/mobile/interfaces.go
pkg/mobile/mockBindableServices.go
pkg/mobile/mockMobileClient.go
pkg/mobile/secrets.go
pkg/mobile/secrets_test.go
pkg/mobile/types.go
pkg/stub/secretsChangeHandler.go
pkg/stub/secretsChangeHandler_test.go
pkg/web/buildConfigsHandler.go
pkg/web/deleteMobileClientHandler.go
pkg/web/deleteMobileClientHandler_test.go
pkg/web/mobileClientsHandler.go
pkg/web/mobileClientsHandler_test.go
pkg/web/router.go
pkg/web/serverConfigHandler_test.go
pkg/web/serviceBindingsHandler.go
pkg/web/serviceBindingsHandler_test.go
pkg/web/types.go
ui/package-lock.json
ui/package.json

deleted
https://issues.jboss.org/browse/AEROGEAR-8141
Remove all the data associated with an app when it's been deleted.
see jira
Add label to bindings, build configs and secrets that are created for an app. When the app is delete, use the label to find the data that should be removed with the app
1. Provision some services and bind an app to the services.
2. Make sure you can see the bindings in the OpenShift web console
3. Remove the app
4. You should see the bindings are removed as well in OpenShift web console.

 🎨 make sure the data associated with an app is removed when the app is

---

pkg/mobile/bindableServices.go
pkg/mobile/bindableServices_test.go
pkg/mobile/types.go
ui/src/DataService.js
ui/src/actions/serviceBinding.js
ui/src/components/mobileservices/BindingPanel.test.js
ui/src/components/mobileservices/BoundServiceRow.js
ui/src/components/mobileservices/BoundServiceRow.test.js
ui/src/components/mobileservices/MobileServiceView.js
ui/src/containers/DeleteItemButton.js
ui/src/models/index.js
ui/src/models/mobileservices/mobileservice.js
ui/src/models/mobileservices/servicebinding.js
ui/src/reducers/serviceBindings.js
ui/src/reducers/serviceBindings.test.js

Can't reopen https://github.com/aerogear/mobile-developer-console/pull/146
So, opened this one

Aerogear 8137 wl 2

---

pkg/web/serverConfigHandler.go
ui/src/components/create_client/EditMobileClientBaseClass.js
ui/src/containers/ClientEditBaseClass.js

https://issues.jboss.org/browse/AEROGEAR-8208

 🐛 create the app when enter button is pressed

---

Gopkg.lock
README.md
integration_tests/bindings/index.js
integration_tests/package-lock.json
integration_tests/package.json
integration_tests/runner.test.js
integration_tests/util/bindingUtils.js

https://issues.jboss.org/browse/AEROGEAR-8161
Follow updated steps in README to run the integration tests:
1. Build the API Server: `make build`
2. Follow [these instructions](#Run-locally) to target existing OpenShift project (**Note:** the project must not contain existing mobile clients)
3. Provision Metrics service in the OpenShift project that you target
4. Install dependencies: `cd integration_tests && npm install`
5. Run the tests: `npm test`

Integration tests for bindings

---

ui/package-lock.json
ui/src/components/overview/MobileClientCardView.scss
ui/src/components/overview/MobileClientCardViewItem.js

https://issues.jboss.org/browse/AEROGEAR-8171
- Added created label with creation date
- Moved services icons inside the card (centered vertically and horizontally)
- Moved build info to the footer

Update UI of app overview screen tiles

---

.circleci/config.yml
scripts/yml/aerogearcatalog_registry.yaml

Use the released tags in the ASB config

 🔖 use release tags in asb config

---

ui/src/components/overview/MobileClientCardView.scss
ui/src/components/overview/MobileClientCardViewItem.js

Issue: https://issues.jboss.org/browse/AEROGEAR-8231
This bug was a regression introduced with https://github.com/aerogear/mobile-developer-console/pull/151
1. open Overview page of MDC
2. create a mobile app
3. try to click on app's menu button (3 dots): you should have `edit` and `delete`
4. try to click elsewhere into the card: it should open the app details

Fixed link to detail page

---

ui/src/components/mobileservices/BindingPanel.js

Fixed bad title in the  service binding dialog.

Fixed service binding dialog title

---

e2e_tests/package-lock.json
e2e_tests/package.json
e2e_tests/test.js

https://issues.jboss.org/browse/AEROGEAR-8205

Added e2e tests

---

integration_tests/bindings/index.js
integration_tests/util/bindingUtils.js
integration_tests/util/sendRequest.js

https://issues.jboss.org/browse/AEROGEAR-8227
https://issues.jboss.org/browse/AEROGEAR-8226

Added binding integration test for app deletion and UPS

---

integration_tests/bindings/index.js
integration_tests/package-lock.json
integration_tests/package.json
integration_tests/runner.test.js
integration_tests/util/awaitTimeout.js
integration_tests/util/bindingUtils.js
integration_tests/util/websockets.js
integration_tests/websockets/index.js

https://issues.jboss.org/browse/AEROGEAR-8228
Integration tests for WebSocket based updates on application and services.
There was none yet.
Call is done to create app, add/remove binding and it's watched whether change occurs.
0. Configure mobile-developer-console against OpenShift with Mobile Metrics service deployed 
1. Go to `integration_tests` and launch `npm install && npm test`
2. Tests should proceed ok
https://mobile-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/mdc-integration-test/69/console

Integration tests websocket updates

---

ui/src/components/mobileservices/BindingStatus.js
ui/src/components/mobileservices/BoundServiceRow.js
ui/src/components/mobileservices/MobileServiceView.js
ui/src/components/mobileservices/UnboundServiceRow.js

JIRA: https://issues.jboss.org/browse/AEROGEAR-8280
When creating a new binding, the create binding window did not close automatically when the binding was done

Fixed windows automatically closing when binding finishes

---

scripts/yml/aerogearcatalog_registry.yaml

Changed version to 1.0.0

---

.circleci/config.yml
Makefile
pom.xml
ui/.gitignore
ui/assembly.xml
ui/pom.xml

So that the UI can be built in MEAD.
Add maven files (pom.xml, assembly.xml).
So that it can be built in MEAD.
By adding maven pom.xml and assembly.xml files.
We'll be able to remove these in future when we no longer need to wrap
npm in maven in MEAD.

📦 Add maven files for building UI in MEAD

---

README.md
scripts/install_yq.sh
scripts/minishift.sh
scripts/post_install.sh

Verification:
1. Comment out line with [post install script](https://github.com/aerogear/mobile-developer-console/blob/master/scripts/minishift.sh#L24)
2. Run `./scripts/minishift.sh`
3. Stop docker app
4. Run `./scripts/post_install.sh`

feat: install yq if docker not present

---

ui/src/components/configuration/sdk-config-docs/cordova.js
ui/src/components/configuration/sdk-config-docs/ionic.js

https://issues.jboss.org/browse/AEROGEAR-8502
Modified integrated docs to reflect changes made in aerogear-js-sdk from 2.1.0-rc3
Because of changes in https://github.com/aerogear/aerogear-js-sdk/pull/230
Only initialization of SDK and small fixes.
1. Launch MDC
2. Go to `Mobile Apps >> yourapp`
3. In `Mobile Services` tab bind all available services - IDM, Sync, Metrics, Push
4. Check the documentation for Ionic and Cordova in `Configuration` tab

feat: integrated docs changed to reflect aerogear-js-sdk API changes

---

ui/src/components/configuration/sdk-config-docs/cordova.js
ui/src/components/configuration/sdk-config-docs/ionic.js

 💚 Fix CI Build

---

ui/src/components/mobileservices/BindingPanel.js
ui/src/components/mobileservices/BoundServiceRow.js
ui/src/components/mobileservices/UnboundServiceRow.js

misc: fixing styles

---

ui/src/components/mobileservices/BoundServiceRow.js

Fixes https://issues.jboss.org/browse/AEROGEAR-8753
Verification:
* Create an app
* Bind it to e.g. Keycloak
* Make sure the info you see has a good layout when bound service is expanded
* Play around with the browser window size to verify things still look good
Check the JIRA for the description of the problem

AEROGEAR-8753 - Cosmetic problem in MDC app's services ui

---

Dockerfile.rhel7
ui/pom.xml

These were updated in PR #203, but we don't yet have the new versions
in the build system where we do the maven build here.

⬇ Downgrade maven plugin versions

---

renovate.json

ignore maven plugins update

---

renovate.json

Renovate ignore deps

---

.circleci/config.yml

add missing step in circleci file for docker

---

renovate.json

prevent renovate bot updating some deps

---

src/components/overview/MobileClientCardView.css
src/components/overview/MobileClientCardView.scss

Issue [AEROGEAR-9293](https://issues.jboss.org/browse/AEROGEAR-9293)

Fixed issue AEROGEAR-9293

---

deploy/services/keycloak/install.yaml
deploy/services/keycloak/operator.yaml
deploy/services/keycloak/rbac.yaml
package-lock.json
package.json
server/appconfig.js
server/mobile-services-info.js
server/server.js
src/actions/apps.js
src/components/configuration/ConfigurationView.js
src/containers/Client.js
src/models/mobileservices/keycloakrealmcr.js
src/reducers/apps.js
src/reducers/index.js
src/reducers/resource.js
src/services/appconfig.js

To verify:
1. Make sure you have an openshift cluster running somewhere, and create a new project.
2. Login to the cluster using `oc`
3. Provision the keycloak operator using the templates provided in this PR:
```
oc create -f ./deploy/services/keycloak/rbac.yaml
oc create -f ./deploy/services/keycloak/operator.yaml
oc create -f ./deploy/services/keycloak/install.yaml
```
4. You should see a keycloak instance will be provisioned.
5. Check the README file for setup the development environment. 
6. Go to the MDC and create a new app. Go to the services page and bind the app to IDM.
7. You should see the content of `mobile-services.json` file updated once the app is bound to the service.

add a new endpoint to return client config

---

Makefile
package.json
server/appconfig.js
server/mobile-services-info.js
server/server.js
src/components/configuration/ConfigurationView.js
src/components/mobileservices/validator/rules/RegExpRule.js
src/components/mobileservices/validator/rules/ValidationRule.js
src/models/mobileservices/customresourcefactory.js
src/models/mobileservices/datasync.js
src/models/mobileservices/mobileservice.js

https://issues.jboss.org/browse/AEROGEAR-9291
1. Run this branch. Create a new mobile app or use an existing one.
2. Go to the services page and you should see there is a `Data Sync` service.
3. Bind the `Data Sync` service. Fill the values in the binding step.
4. Once it's finished, go to the configuration page and you should see the content of `mobile-services.json` file is updated.
5. Go back to the services page and delete the binding for data sync
6. Check the content of `mobile-services.json` file and it should be updated again.

Aerogear 9291 data sync

---

deploy/mobile-developer-console.template.yaml
server/server.js
src/actions/services.js
src/components/mobileservices/BindingPanel.js
src/services/openshift.js

Fix the following issues:
1. Error in [this comment](https://github.com/aerogear/mobile-developer-console/pull/250#issuecomment-497253878)
2. If an app is bound to services, when the app is deleted and re-created, the bound services are still there.
To verify:
1. Click on an app from the overview page, and there shouldn't be error reported anymore.
2. Bind a service to the app, delete the app, recreate it again with the same name and you should see there are no bound services for the app.

make sure set the owner references field on the resources

---

deploy/services/keycloak/keycloak-crd.yaml
deploy/services/keycloak/keycloak-realm-crd.yaml
scripts/development.sh
scripts/prepare.sh
server/server.js

Update the `prepare.sh` script to provision the services.
To verify:
* run `prepare.sh` script and it should provision keycloak into a namespace

setup keycloak service during prepare step

---

package-lock.json
src/components/overview/MobileClientCardView.test.js

https://issues.jboss.org/browse/AEROGEAR-9297
Updated unit test file for the `MobileClientCardView` component. Increased coverage from ~50% to 100%.
1. run `npm run coverage`.
2. If you encountered issues with step 1, please run `npm run build-css` and repeat step 1.
3. View the line for MobileClientCardView.js. It should show coverage at 100% for this file.

Updated unit test for MobileClientCardView component; increased coverage to 100%

---

Makefile
README.md
deploy/deploy-image-stream.sh
scripts/development.sh
scripts/minishift_start.sh

https://issues.jboss.org/browse/AEROGEAR-9282
Small fixes/additions to readme & scripts
Verify that steps for setting up local environment are still valid by following the guide [here](https://github.com/aerogear/mobile-developer-console/pull/257/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)

fix: readme, scripts, image push

---

src/components/build/BuildConfigDetails.test.js
src/components/build/BuildPipelineStage.test.js

https://issues.jboss.org/browse/AEROGEAR-9330
Created a new test suite for the `BuildPipelineStage` component.
1. Run `grep 'Lines\|BuildPipeline*'`
2. Tests should passa and coverage should be at 100%.

test: added missing test suite for BuildPipelineStage component

---

package-lock.json
package.json
src/actions/apps.test.js
src/services/openshift.js
src/setupTests.js

https://issues.jboss.org/browse/AEROGEAR-9432
Added tests for `src/actions/apps.js`.
There were no tests.
Mocked Axios calls with [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter).
1. Run `npm run coverage | grep 'Lines\|apps.js`.
2. All tests should pass.

test(actions): added apps actions tests

---

package-lock.json
package.json
src/actions/apps.test.js
src/components/build/MobileClientBuildListItem.js
src/components/build/MobileClientBuildListItem.test.js
src/services/openshift.js
src/setupTests.js

https://issues.jboss.org/browse/AEROGEAR-9382
- Added unit tests for the `MobileClientBuildHistoryList` component.
- Removed unused code in component.
There were no tests for this file.
1. Run `npm run coverage | grep 'Lines\|MobileClientBuildHistoryList'`
2. Tests should pass and coverage should be at 100%.

test: added tests for MobileClientBuildHistoryList component

---

integration_tests/util/bindingUtils.js
server/appServices.js
server/mobile-services-info.js
server/server.js
src/actions/services.js
src/models/mobileservices/customresourcefactory.js
src/models/mobileservices/mobilesecurityserviceappcr.js

https://issues.jboss.org/browse/AEROGEAR-9473
https://issues.jboss.org/browse/AEROGEAR-9470
https://issues.jboss.org/browse/AEROGEAR-9492
https://issues.jboss.org/browse/AEROGEAR-9478
https://issues.jboss.org/browse/AEROGEAR-9477
1. Created a wizard form that allows the developer to bind their app to the Mobile Security Service.
2. Update the `mobile-services.json` config with the MSS config.
3. Create a MobileSecurityServiceApp custom resource.
4. The MSS will only show as an available binding if the custom resource exists in the namespace specified in `MSS_NAMESPACE`.
To fulfil acceptance criteria.
1. Ensure that the Mobile Security Service is provisioned. You can use the …

Added ability to bind the Mobile Security Service to an app.

---

src/components/configuration/InlineEdit.js

Add references to relevant tickets or a short description about what motivated you do it. (E.g JIRA: https://issues.jboss.org/browse/AEROGEAR-{} AND/OR ISSUE: https://github.com/aerogear/standards/issues/{}) 
Add an short answer for: What was done in this PR? (E.g Don't allow users has access to the feature X.)
Add an short answer for: Why it was done? (E.g The feature X was deprecated.)
1. Go to `XX >> YY >> SS`
2. Create a new item `N` with the info `X`
3. Try to edit this item 
4. Check if in the left menu the feature X is not so long present.
PS.: Add images and/or .gifs to …

revert: Refactor(InlineEdit): removal of unsed component InlineEdit

---

src/actions/services.js

https://issues.jboss.org/browse/AEROGEAR-9181
Only watch the services that are not disabled.
Prevents error from being shown when it shouldn't be and prevents unnecessary websocket connection attempts.
1. Run MDC. Do not include the `MSS_NAMESPACE` and `MSS_APPS_NAMESPACE`.
2. Click an app.
3. No 404 error message should appear as MDC did not try to watch MSS.

fix: dont watch disabled services

---

src/components/mobileservices/validator/rules/RegexpRule.test.js

https://issues.jboss.org/browse/AEROGEAR-9558 
Added tests to cover the `RegExpRule` class.
1. Run `make test`. Tests should pass.

test(RegexpRule): added basic tests

---

src/actions/apps.test.js
src/actions/buildConfigs.test.js
src/actions/builds.test.js

#307 : Since the promises were not being returned the tests would pass when they should fail.

fix: return promise

---

src/components/common/Duration.test.js

https://issues.jboss.org/browse/AEROGEAR-9560
Add test coverage to components/common/Duration.js
To increase the test coverage
Added Duration.test.js to **components/common/**
1. Run `npm run test'
2. All test should pass
3. Coverage of file increased

test(duration.js): Added tests for components/common/Duration.js

---

src/components/mobileservices/validator/rules/NoopRule.test.js
src/components/mobileservices/validator/rules/SameValueOfRule.test.js
src/components/mobileservices/validator/rules/ValidationRule.test.js

https://issues.jboss.org/browse/AEROGEAR-9561
Add test coverage to SameValueOfRule.js
To increase the test coverage.
Added SameValueOfRule.test.js to **components/mobileservices/validator/rules**
1. Run `npm run test`
2. All tests should be passing

test(SameValueOfRule): Basic tests added

---

src/components/mobileservices/validator/RuleSetValidator.js
src/components/mobileservices/validator/RuleSetValidator.test.js

https://issues.jboss.org/browse/AEROGEAR-9582
Added tests around RuleSetValidator
To increase test coverage
By adding extra test to ruleSetValidator.test.js
1. run `npm run test`
2. all tests should be passing

test(RuleSetValidator): Added tests around RuleSetValidator

---

server/android-variant-crd.json
server/appServices.js
server/ios-variant-crd.json
server/mobile-services-info.js
server/push-application-crd.json
server/server.js

https://issues.jboss.org/browse/AEROGEAR-9436
Created the client config for UPS and added it to the app's status.
The config is built from the PushApplication, IOSVariant and AndroidVariant custom resources.
1. Ensure that the UPS operator is installed and running on your cluster. See [here](https://gist.github.com/aliok/4c679a888519eebe63324dded9ff2362) for how to do this.
3. Create an app in MDC.
4. Bind the Push Notification service to your app.
5. Bind the AndroidVariant and IOSVariants separately. Each time, check if `mobile-services.json` contents matches the variants which are currently bound.
This is not so much an issue, but when a variant is added or removed, the following error shows:
```
Failed to update app …
```

feat: update `mobile-services.json` with UPS config

---

server/appServices.js

https://issues.jboss.org/browse/AEROGEAR-9607
[godaddy/kubernetes-client](https://github.com/godaddy/kubernetes-client) watch closes after an indertminate amount of time, on **custom** resources only. This fixes that by listening for the close event and reopening it.
See https://github.com/godaddy/kubernetes-client/issues/520
The streams were closing prematurely on CRs which prevented the MDC from updating to reflect the actual state.
1. Run MDC.
2. Create an app. Bind the Push Notification service and bind both variants.
3. Leave MDC for 2-3 minutes and try to unbind again.
4. `mobile-services.json` should update.

fix(kubeclient): keep watch open on CRDs

---

src/models/mobileservices/mobilesecurityserviceappcr.js

https://issues.jboss.org/browse/AEROGEAR-9502
Added a link to the Mobile Security Service documentation.

feat(docs-link): add link to MSS docs

---

server/appServices.js
server/helpers.js
server/mobile-services.js
server/server.js

https://issues.jboss.org/browse/AEROGEAR-9634
Save the URL/route to the UPS application in the `mobile-services.json` file.
2. Bind Push Notification.
3. Check `mobile-services.json`. It should look like this:
```json
{
"clientId": "myapp",
"namespace": "mobile-console",
"services": [
{
"config": {
"android": {
"variantId": "b51c3d63-9007-456b-8704-1b29a39e6198",
"variantSecret": "9081e771-9dd1-4e35-b992-bcd5a0bfdeb9"
}
},
"id": "3a06a190-aeb3-11e9-ae5a-525400ccd749",
"name": "push",
"type": "push",
"url": "https://192.168.42.179:8443" // note the URL
}
]
}
```
PS.: Add images and/or .gifs to illustrate what was changed if this pull request modifies the appearance/output of something presented to the …

feat: display UPS url in config

---

server/appServices.js

https://issues.jboss.org/browse/AEROGEAR-9602
Removed deprecation warnings for [godaddy/kubernetes-client](https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md) library.
1. Run the MDC server: `OPENSHIFT_HOST=$(minishift ip):8443 OPENSHIFT_USER_TOKEN=$(oc whoami -t) npm run start:server`
2. There should be no deprecation warnings in the console.
3. Run the MDC UI. MDC should still work as normal.
This is a follow-up to https://github.com/aerogear/mobile-developer-console/pull/331 - as we were waiting for https://github.com/godaddy/kubernetes-client/issues/517 to be resolved for this to become possible. 
https://github.com/godaddy/kubernetes-client/pull/524

refactor(kubeclient): remove deprecation warnings

---

src/models/mobileservices/mobilesecurityserviceappcr.js

Changed the text of the label to match the other services.

fix: change label text

---

server/mobile-services.js
src/models/mobileservices/mobilesecurityserviceappcr.js

Depends on https://github.com/aerogear/mobile-security-service-operator/pull/155

Fix aerogear.com

---

src/models/mobileservices/keycloakrealmcr.js

Add references to relevant tickets or a short description about what motivated you do it. (E.g JIRA: https://issues.jboss.org/browse/AEROGEAR-{} AND/OR ISSUE: https://github.com/aerogear/standards/issues/{}) 
Add an short answer for: What was done in this PR? (E.g Don't allow users has access to the feature X.)
Add an short answer for: Why it was done? (E.g The feature X was deprecated.)
1. Go to `XX >> YY >> SS`
2. Create a new item `N` with the info `X`
3. Try to edit this item 
4. Check if in the left menu the feature X is not so long present.
PS.: Add images and/or .gifs to …

fix: AGMS-635 - keycloak client config issues

---

src/components/configuration/sdk-config-docs/cordova.js
src/components/configuration/sdk-config-docs/ionic.js

https://issues.jboss.org/browse/AGMS-618
text fix
Just make sure that you don't have undefined after binding sync.

Fixing minor typo

---

server/appServices.js

https://issues.jboss.org/browse/AEROGEAR-9668
`mobile-services.json` will stop updating after a number of minutes (30+). This is because of the `--min-request-timeout` flag in kube-apiserver. See https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/.
This fix reopens the watch endpoint on each of the mobile services when the stream detects an endpoint getting closed.
This is hard to verify since the Mobile Developer Console needs to be running uninterrupted for a long time before the watches close. I suggest you follow the steps below, but also leave it for another 30 minutes afterwards to see if it is still working.
1. Ensure MDC is running for a long time (> 40 minutes to be sure).
2. Create an app and try to bind Mobile Security.
3. Check …

fix(mobile-services): re-open streams after they automatically close

---

integration_tests/package.json

https://issues.jboss.org/browse/AGMS-651
- Upgrade lodash from 4.17.11 to 4.17.13 and axios from 0.18.0 to 0.18.1 in integration tests
Solve the following CEVs
- https://github.com/aerogear/mobile-developer-console/network/alert/integration_tests/package-lock.json/lodash/open
- https://github.com/aerogear/mobile-developer-console/network/alert/integration_tests/package-lock.json/axios/open
Has no break changes, so please check the CI only. 

Upgrade lodash from 4.17.11 to 4.17.13 and axios from 0.18.0 to 0.18.1 in integration tests

---

integration_tests/package-lock.json
package-lock.json

AGMS Jiras. 
Regenerated the package-lock.json file.
It has been not updated, probably because of the usage of the old version of npm. Just it probably will solve a big part of the vulnerabilities without break changes. 
- Update the local npm vrsion used
- remove the lock 
- run npm install and let it be generated automatically
PS.: It was done for the integration-tests as well. 
- Run it locally
- Check the CI

fix( package-lock) was outated regards  package.json

---

package-lock.json
package.json

ISSUE: 
- https://issues.jboss.org/browse/AGMS-647
- https://issues.jboss.org/browse/AGMS-652

Fixed set-value security issue

---

src/models/mobileservices/keycloakrealmcr.js

https://issues.jboss.org/browse/AGMS-702

fix: inconsistencies in keycloak clients

---

server/mobile-services.js

Took over #359 to rebase and merge

Fixed websocket url for insecure routes

---

server/appServices.js

This change returns the result of a promise. Previously the final result was not returned at all.

refactor: return promises

---

server/appServices.js

This fixes an issue when Kubernetes API restarts while the Node server is running, which causes the atches on the resources to fail. 
This retries the watches for n (default 10) times before exiting the application.
1. Run the MDC server against your remote cluster.
2. SSH into the master node.
3. Restart the API and controllers:
```sh
/usr/local/bin/master-restart api
```
and
```sh
/usr/local/bin/master-restart controllers
```
Watch the logs from MDC. You should see the server failing to attempting to set up the watch on the resources again, eg:
```
waiting 3000 milliseconds before attempting services watches again
```
Once it has successfully reconnected you should see `connection successful`.
4. Refresh MDC and try to bind a service. It should be successful.

fix: enable server to retry connecting to kube api

---

src/components/create_client/EditMobileClientBaseClass.js
src/models/index.js
src/models/mobileapps/mobileapp.js

https://issues.jboss.org/browse/AEROGEAR-9768
Added max length validation to the app name.
1. Try to create an app > 70 characters. It should be prevented.

refactor: added max length validation

---

src/components/create_client/EditMobileClientBaseClass.js

https://issues.jboss.org/browse/AGMS-623
The error message did not fully explain what is an acceptable app name format.
* Name can't begin or end with a special character.
* Hyphens are accepted.
1. Open the Create App dialog.
2. Enter an invalid name.
3. Inspect the error message for incompleteness or spelling mistakes.

refactor(error-message): improve error message

---

src/components/mobileservices/BindingPanel.js

Update the wizard to pf4
Continue PF4 conversion effort
1. Run a local build
2. Create a new app
3. Test the mobile client page

Convert wizard to pf4

---

install-mobile-services.sh
src/components/mobileservices/MobileServiceView.js
src/style/index.css

Adds script for all services and updates style for multiple data lists

fix multiple data list entries

---

src/components/mobileservices/BoundServiceRow.js
src/components/mobileservices/MobileServiceView.js
src/components/overview/MobileClientCardView.css
src/components/overview/MobileClientCardView.scss
src/components/overview/MobileClientCardViewItem.js
src/containers/Client.css
src/containers/Client.scss
src/containers/Configuration.js

revised style and updates

---

src/components/mobileservices/BindingPanel.js

Update wizard results design

---

src/containers/Client.js

closes #409 
Removes the modal and button components

Remove functionality to update name 

---

src/components/mobileservices/MobileServiceView.js

update name for available services

---

src/components/App.js
src/components/configuration/ConfigurationView.css
src/components/configuration/ConfigurationView.scss
src/components/mobileservices/BindingPanel.js
src/components/mobileservices/BoundServiceRow.js
src/components/mobileservices/MobileServiceView.js
src/components/mobileservices/UnboundServiceRow.js
src/components/overview/MobileClientCardView.js
src/components/overview/MobileClientCardViewItem.js
src/containers/Client.js
src/containers/ClientEditBaseClass.js
src/containers/Configuration.js

This fixes copy clipboard to not longer display JSON as [Object] ( #411 ).  Also fixes linting issues.
- [ X] Code has been tested locally by PR requester

Fixes CopyClipboard issue and linting errors

---

src/components/mobileservices/BindingPanel.js

Fix wizard form validation

---

package-lock.json
package.json
src/containers/Client.js

pull in latest from react to update the clipboard

pull in latest from react to update the clipboard

---

package-lock.json
package.json
server/appServices.js
server/mobile-services.js
server/server.js
server/web-variant-crd.json
src/components/mobileservices/BoundServiceRow.js
src/components/mobileservices/BoundServiceRow.test.js
src/components/mobileservices/validator/rules/CompositeRule.js
src/components/mobileservices/validator/rules/CompositeRule.test.js
src/components/mobileservices/validator/rules/MaxLengthRule.js
src/components/mobileservices/validator/rules/ValidEmailRule.js
src/components/mobileservices/validator/rules/ValidEmailRule.test.js
src/components/mobileservices/validator/rules/ValidMailToRule.js
src/components/mobileservices/validator/rules/ValidMailToRule.test.js
src/components/mobileservices/validator/rules/ValidUrlRule.js
src/components/mobileservices/validator/rules/ValidUrlRule.test.js
src/components/mobileservices/validator/rules/ValidateECDSAKey.js
src/components/mobileservices/validator/rules/ValidateECDSAKey.test.js
src/components/mobileservices/validator/rules/ValidationRule.js
src/components/mobileservices/validator/rules/ValidationRuleBaseClass.js
src/models/mobileservices/pushvariantcr.js
src/services/crmanagers/ResourceManagerFactory.js

https://issues.jboss.org/browse/AEROGEAR-9987
Add support in the MDC for web push with UPS
- Added a new wizard page for the WebPush variant
- Added the following fields validator rules:
- CompositeRule: it is a new rule that allow to specify a list of subrules and an evaluation algorithm whose value can be either `all` (all of the subrules must succeed) or `any` (at least one of the subrules must succeed)
- ValidEmailRule
- ValidUrlRule
- ValidMailToRule
- ValidECDSARule
Web push is a new feature in UPS
By following the similar steps of the other push features 
1. Have MDC running with UPS that supports web push
2. Create an app 
3. Bind UPS using web push.
4. Check that the `mobile-service.json` gets updated
5. Check icon is shown on the home page.
6. Create new app
7. Bind both Android …

Aerogear 9987

---

src/components/App.js
src/components/MDCAboutModal.js
src/components/overview/MobileClientCardView.js
src/components/overview/MobileClientCardViewItem.js
src/configureStore.js

Added versions to the about modal
(Also cleaned up a few unnecessary comments.)

Add versions to about modal

---

package-lock.json
package.json
src/components/App.js
src/components/MDCAboutModal.js
src/components/create_client/EditMobileClientBaseClass.js
src/components/create_client/VerticalFormField.js
src/components/mobileservices/BindingPanel.js
src/components/overview/MobileClientCardView.css
src/components/overview/MobileClientCardView.js
src/components/overview/MobileClientCardView.scss
src/components/overview/MobileClientCardViewItem.js
src/configureStore.js
src/containers/Client.js
src/containers/ClientEditBaseClass.js
src/containers/DeleteItemButton.js

Added chips to toolbar, used PF4 DataToolbar with chips

Add chips to toolbar

---

public/img/RH-Mobile-DevConsole-Logo.svg
public/img/aerogear_logo.svg
src/components/App.js
src/components/overview/MobileClientCardView.css
src/components/overview/MobileClientCardView.js
src/components/overview/MobileClientCardView.scss
src/models/mobileservices/datasync.scss

Fix remaining problems seen here: https://mdc-mdc-proxy-mobile-developer-console.apps.boston-3adf.open.redhat.com/overview

Fix styles

---

public/img/RH-Mobile-DevConsole-Logo.svg
src/components/mobileservices/BindingPanel.js
src/components/mobileservices/BindingPanel.test.js

Fixes wizard updates and logo width

Final fixes

---

src/components/App.js
src/components/create_client/CreateClient.test.js
src/components/create_client/EditMobileClientBaseClass.js
src/components/mobileservices/BindButton.test.js
src/components/mobileservices/BindingPanel.test.js
src/components/mobileservices/BoundServiceRow.test.js
src/components/mobileservices/MobileServiceView.js
src/components/mobileservices/MobileServiceView.test.js
src/components/overview/MobileClientCardView.js
src/components/overview/MobileClientCardView.test.js
src/components/overview/MobileClientCardViewItem.test.js
src/containers/Client.test.js
src/containers/ErrorMessages.test.js

Commented out any outdated tests. These will need to be updated in the future. Also, any remaining linting errors were fixed.

Fix build errors: tests and linting
