- Gopkg.lock
- Gopkg.toml
- deploy/cr.yaml
- deploy/crd.yaml
- deploy/rbac.yaml
- mobile-client-service.template.yaml
- pkg/apis/aerogear/v1alpha1/doc.go
- pkg/apis/aerogear/v1alpha1/register.go
- pkg/apis/aerogear/v1alpha1/types.go
- pkg/mobile/mobileClient.go
- pkg/web/mobileClientsHandler.go
Update the CRD to match the one that we currently have in [mobile-core](https://github.com/aerogear/mobile-core/blob/master/installer/roles/create-mobile-client-crd/files/mobile-client-crd.yaml).
This way we don't need to create a separate one.
@sedroche @StephenCoady mind taking a look?
>  🎨 reuse the existing CRD

- ui/src/components/common/CopyToClipboardMultiline.scss
CopyToClipboard component was not properly styled - copy button was placed outside of the element.
> Fix for copyToClipboard component styling

- pkg/stub/handler.go
Backend outputs unnecessary info logs about `invalid secret`s.
> Removed unnecessary log

- cmd/api-server/main.go
- pkg/mobile/build.go
- pkg/mobile/build_test.go
- pkg/mobile/interfaces.go
- pkg/web/buildsHandler.go
- pkg/web/buildsHandler_test.go
- ui/src/components/build/BuildSummary.js
- ui/src/components/build/MobileClientBuildHistoryList.js
https://issues.jboss.org/browse/AEROGEAR-7979
💁‍♂️  Feel free to use [my project on community cluster](https://community.skunkhenry.com/console/project/psturc-test/overview) (ping me for user/pass if you don't have it)
1. Make sure the OpenShift project you are targeting has Mobile CI/CD provisioned and also has some existing builds
1. In MDC, go to Builds, click on Build and verify all links (`Build #x`) are pointing to the correct page in OpenShift Console (also check those in build history)
> Add openshiftMasterURL to list of builds

- pkg/web/wsHandler.go
- scripts/development.sh
- ui/package-lock.json
In production it should check origin for websocket connections.
- only disable origin check for debug
- print output of backend to console in debug mode
> Websockets - no origin check in debug mode

- cmd/api-server/main.go
- pkg/web/router.go
- pkg/web/types.go
- pkg/web/userHandler.go
- pkg/web/userHandler_test.go
- ui/package-lock.json
- ui/src/DataService.js
https://issues.jboss.org/browse/AEROGEAR-7992
Show the current logged in user name in the console
The openshift oauth proxy will forward the username & email info in the request headers. We just need to retrieve them and return back to the client.
1. Provision the MDC from the service catalog. Make sure the oauth proxy provisioned to protected the service.
2. Login to the service. You should see your name show up in the top right corner.
> add route for user info

- pkg/apis/aerogear/v1alpha1/types.go
- pkg/web/types.go
- ui/src/components/overview/MobileClientCardView.js
https://issues.jboss.org/browse/AEROGEAR-7995
Remove the mock data for services
Show the actual bound services for an app
The bound services of an app are available from the `status.services` field of an app. So we just use it.
1. Get this branch running and point it to a Openshift cluster
2. Create a new app. 
3. You can try provision some mobile services and bind them to the app, but it may not work all the time. A simple way is to use oc to edit the newly created mobile app:
````
oc edit mobileclient <appname> -o json
````
then edit the json file to add new services to the status.services field. An example:
```
"services": [
{
"config": {},
"id": "push",
"name": "push",
"type": "push",
"url": "http://pushserver.com",
"version": "1"
},
{
"config": {},
"id": "keycloak",
"name": …
```
>  💄use service data

- ui/package-lock.json
- ui/package.json
- ui/src/components/build/MobileClientBuildListItem.js
- ui/src/components/build/MobileClientBuildListItem.scss
- ui/src/components/common/CopyToClipboardMultiline.js
- ui/src/components/configuration/ConfigurationView.js
- ui/src/components/configuration/ServiceSDKInfo.js
- ui/src/setupProxy.js
Updated react-scripts to allow for debugging in react tests.
Updated react-scripts to allow for debugging in react tests.
Updated react-scripts to allow for debugging in react tests.
Updated package.json, proxy part is no longer compatible with new `react-scripts`.
Proxy server settings script is moved to `setupProxy.js` using http-proxy-middleware. That's recommended by `react-scripts`.
1. Start with `./scripts/development.sh`
2. Check if everything works fine
> Updated react-scripts

- README.md
- scripts/minishift.sh
- scripts/oc-cluster-up.sh
- scripts/setup-router-certs.sh
Currently for mac users we don't have recommendation for how to setup mobile.next with local OpenShift. The problem with minishift was with certificates installed on router by default. Because of this issue Android/iOS prevented communication with services running in OpenShift. This PR adds script that will set up minishift with correct certificates.
1. `./scripts/minishift.sh`
2. deploy mdc and keycloak
3. create app and bind it with keycloak
4. verify that showcase app can communicate with keycloak
> Added minishift and oc-cluster-up install scripts

- ui/src/components/mobileservices/MobileServiceView.js
During the review John asked if the client ID could be set by default.  Now it is.
The default client id is set when MobileServiceView is building the unbound service row objects.
Usability.
The default client id is set when MobileServiceView is building the unbound service row objects.  The function is wrapped in a try catch block that does minimal logging.  Worst case scenario is the user has to input this value themself.
When you try to bind a mobile service, you should see on the second page of the wizrd that client id is now prefilled.
> Setting default client id for binding properties

- README.md
- scripts/minishift.sh
- scripts/oc-cluster-up.sh
- scripts/setup-router-certs.sh
`oc-cluster-up` script was not properly tested when added. This PR should fix this script. Tested here https://mobile-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/mobile-next-test/22/console
- cluster ip can now be provided to the script (needed for ci)
- added `no-proxy` flag for `oc cluster up` (needed in ci environment)
- additional services (e.g. ansible-service-broker) installed separately from `oc cluster up` - this enables rerunning the script
- make sure temporary files are editable with `post-install` script (were blocked by se-linux)
- fix `setup-router-certs` script for oc cluster up
> oc-cluster-up fix

- ui/package-lock.json
- ui/src/reducers/buildConfigs.js
Small fix of create build config functionality. When new client was created, state of create build config form is cleared, but it should be reset to its initial state.
Setting initialState instead of empty state.
Functionality was unexpected.
1. Go to some mobile app and Build tab
2. Create new build config (Actions menu or button if list of build configs is empty)
3. After build config is created, try to do it again
4. There should be prefilled Jenkins path ./ and branch `master` under advanced source options. It was empty before that.
> Fix: Create build resets form to initial state, not the empty one

- ui/src/containers/Client.js
- ui/src/containers/Client.test.js
https://issues.jboss.org/browse/AEROGEAR-8127
When the app details page is refreshed, the `configuration` tab is always shown by default
To fix it, update the url with hash value of the page, so that the selected tab will be part of the url
1. Go to the details view of an app, you should see the configuration page by default.
2. Select the `Builds` or `Mobile Services` tab
3. Refresh the page, you should stay on that page.
>  🐛 remember the selected tab on the app details view

- scripts/minishift.sh
- scripts/oc-cluster-up.sh
- scripts/post_install.sh
- scripts/setup-router-certs.sh
https://trello.com/c/zQBCWwKI/25-1-replace-waiting-for-asb-to-spin-up-with-canceling-deployment-in-installer
- canceling of deployment is not supported in oc 3.11
- current implementation checks number of running pods which does not work properly every time
- replaced with deployment status check
https://trello.com/c/Dbyr6z40/42-1-get-name-of-asb-project-in-installer-automatically
Also added condition that checks if ASB was already configured, if so the config is skipped.
> Installer fix - waiting for asb deployment

- ui/src/DataService.js
- ui/src/actions/serviceBinding.js
- ui/src/components/mobileservices/MobileServiceView.js
- ui/src/components/mobileservices/UnboundServiceRow.js
- ui/src/containers/DeleteItemButton.js
- ui/src/models/mobileservices/mobileservice.js
- ui/src/reducers/serviceBindings.js
- ui/src/reducers/serviceBindings.test.js
https://issues.jboss.org/browse/AEROGEAR-8128
1. Click on an existing application to see its details
2. Click on mobile services
3. Bind a new service
5. Verify the the dialog closes and the service is put in 'Binding in progress'
1. Click on an existing application to see its details
2. Click on mobile services
3. If the application has no services bound, bind a new one
4. Delete one bound service
5. Verify the the dialog closes and the service is put in 'Unbinding in progress'
**NOTE:** Currently the service will remain to the `in progress` state until you refresh. @secondsun is working on a Websocket implementation that should receive events from the server
> When delete a service binding, the view is not updated

- pkg/web/mobileClientsHandler.go
- pkg/web/types.go
- ui/src/models/mobileapps/mobileappstatus.js
- ui/src/models/mobileservices/mobileservice.js
https://issues.jboss.org/browse/AEROGEAR-8131
- Removed clusterName from mobile-services.json
- fixed bug where web-app crashes when there is MDC provisioned in currently used project.
> Removed clusterName from mobile-services.json

- ui/src/components/mobileservices/MobileServiceView.js
Populating default binding properties was broken by https://github.com/aerogear/mobile-developer-console/pull/140
> fix: default binding properties

- ui/src/components/mobileservices/BoundServiceRow.js
- ui/src/components/mobileservices/BoundServiceRow.test.js
- ui/src/components/mobileservices/MobileServiceView.js
- ui/src/containers/Client.js
- ui/src/containers/Client.test.js
- ui/src/containers/Overview.js
- ui/src/containers/Overview.test.js
https://issues.jboss.org/browse/AEROGEAR-8149
- watch for bindings in `Client` component (higher in hierarchy) rather than in `MobileServiceView`
- watch also for services in `Client`
- only show spinner in `MobileServiceView` for first fetch (not for every update)
- don't watch for services in Overview page
1. Create app in MDC and open it
2. Provision a mobile service in OpenShift
3. Open Services tab in MDC
4. When the service is provisioned it should show up
1. Create app in MDC and bind it with a service
2. Delete the app
3. There should be no error in browser console
> Fixed watching for resources in UI

- README.md
This step was automated and is not needed anymore.
> Remove ASB project name export step

- .editorconfig
- pkg/mobile/bindableServices.go
- pkg/mobile/types.go
- ui/src/components/mobileservices/BindButton.js
- ui/src/components/mobileservices/BindingPanel.js
- ui/src/components/mobileservices/BindingPanel.test.js
- ui/src/components/mobileservices/BindingStatus.js
- ui/src/components/mobileservices/BoundServiceRow.js
- ui/src/components/mobileservices/BoundServiceRow.test.js
- ui/src/components/mobileservices/MobileServiceView.js
- ui/src/components/mobileservices/ServiceRow.scss
- ui/src/components/mobileservices/UnboundServiceRow.js
- ui/src/models/mobileservices/mobileservice.js
- ui/src/reducers/serviceBindings.js
- ui/src/reducers/serviceBindings.test.js
How to verify:
- Make sure you have the latest UPS apb. If not, change metadata of UPS apb to https://github.com/aerogearcatalog/unifiedpush-apb/blob/master/apb.yml#L32 via `oc edit clusterserviceplan`
- Start this project, Provision UPS, provision Metrics
- Create a client and bind to UPS
- You will still see the Bind button next to UPS, but not for e.g. Metrics when you bind to Metrics
- Press Bind button next to UPS again
- You will only see the missing platform, Android or IOS, in the platform select box
- Create the binding
- You won't see the Bind button next to UPS anymore
- Also test things like "Binding in Progress" status display, etc.
What's missing:
- Delete button adaption for multiple bindings. Will be done separately within a task from …
> AEROGEAR-8137

- pkg/web/buildConfigsHandler.go
- pkg/web/buildsHandler.go
- pkg/web/deleteMobileClientHandler.go
- pkg/web/messages.go
- pkg/web/messages_test.go
- pkg/web/mobileClientsHandler.go
- pkg/web/serverConfigHandler.go
- pkg/web/serviceBindingsHandler.go
- pkg/web/serviceInstancesHandler.go
- ui/src/containers/ErrorMessages.js
https://issues.jboss.org/browse/AEROGEAR-8143
Error messages were directly reported from Kubernetes to the user make the latter receive messages like `mobileclients.mobile.k8s.io "appname" already exists"`
With this PR, the error becomes: `Item identified by 'appname' already exists`
1. Open the mobile developer console
2. try creating one app
3. try creating a new app with the same name as before
4. Check that the error is less _cryptic_
Try to generate other errors in other situation to verify that all the messages has been replaced.
> Better error messages

- ui/src/components/create_client/EditMobileClientBaseClass.js
https://issues.jboss.org/browse/AEROGEAR-8208
Blocking Enter key in create app dialog.
When you pressed it, it would refresh the page without creating the app.
Blocking keypress event in the app name field.
1. Go to overview screen
2. Press `Create Mobile App` 
3. Fill in name
4. Press Enter, it's expected for the dialog not to close.
> Fix: create mobile app Enter key forbidden

- ui/src/components/mobileservices/MobileServiceView.js
- ui/src/components/overview/MobileClientCardViewItem.js
JIRA: https://issues.jboss.org/browse/AEROGEAR-8232
The GUI was not updated automatically to reflect the list of available services (needed to manual refresh) when creating/deleting services from openshift console
Added websocket watcher to check if the list of services was changed
1. create a mobile app
1. open it
1. navigate to services tab
1. in another browser tab open OpenShift console and provision a new service
1. go back to mdc tab
1. check that the new service is visible into the MDC page
1. Try the same by deleting a service
> Added monitoring of services to automatically update bindable services

- scripts/minishift.sh
Improve ~user~ developer experience.
Added a check to verify docker is running before starting minishift and performing other install steps.
If the docker daemon is not active on the machine the `minishift.sh` script will continue running and create a cluster, but ultimately the mobile developer console will not be available.
Added a simple check to verify the docker daemon is running before doing anything else.
The following is an example tested on macOS
1. Kill the docker daemon
2. Run `./scripts/minishift.sh`
3. Note errors such as `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
4. Note that the script still completes and reports success despite errors
I can move the check elsewhere, but it makes sense to run it ASAP.
> 🐛 fix: verify docker is running before starting a cluster

- ui/src/components/mobileservices/BoundServiceRow.js
- ui/src/components/mobileservices/BoundServiceRow.test.js
- ui/src/components/mobileservices/MobileServiceView.js
- ui/src/components/mobileservices/UnboundServiceRow.js
https://issues.jboss.org/browse/AEROGEAR-8248
`BindingPanel` moved from service rows to `ServiceView`.
Seems that BindingPanel gets rerendered, when there is an update from websocket.
> Fix for Input text fields gets emptied when other binding is in progress

- integration_tests/mobile_clients/index.js
This should fix issue in central ci. e2e tests do not cleanup when they finish. So if integration tests will run after that, they will fail. https://mobile-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/mdc-integration-test/57/console
> Fix integration tests - remove all apps before starting the test

- ui/src/components/mobileservices/BindingPanel.js
JIRA:
- https://issues.jboss.org/browse/AEROGEAR-8239
- https://issues.jboss.org/browse/AEROGEAR-8247
- Fixed the wizard so that wizard state is always reset to initial state when opening
- Fixed platform filtering in filling the selectbox
- Fixed method used to list the bound/unbound services to comply with the rest of the MDC
1. Create a new app
2. Bind UPS for iOS to the app
3. Try binding another UPS instance: only android must be available
4. After binding android too, try binding another service: the listbox should be empty (the bind button should disappear. Issue : [AEROGEAR-8273](https://issues.jboss.org/browse/AEROGEAR-8273)
5. Delete the iOS or the Android binding: only the binding for the other platform should be available
6. Delete the last UPS binding: binding for both …
> AEROGEAR-8239

- scripts/yml/aerogearcatalog_registry.yaml
> Bumped aerogearcatalog version to 1.0.0-alpha2 (was 1.0.0-alpha)

- ui/package-lock.json
- ui/package.json
Without these changes, `npm install` doesn't work without extra
flags. The changes in this commit were done by `npm audit fix`. See
below for the output of `npm audit` beforehand:
```
npm audit
=== npm audit security report ===
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Missing Origin Validation                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ react-scripts                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ …
```
> 🔒 Update dependencies for `npm-audit` failures

- ui/package-lock.json
- ui/package.json
require-uncached is deprecated, and for some reason Verdaccio
registries don't want to cache that (probably any deprecated
package). Updating eslint (and react-scripts because that also pulls
in eslint) fixes this because it now uses import-fresh instead of
require-uncached.
> ⬆ Upgrade npm deps to not use require-uncached

- ui/node_modules/.hooks/preinstall
- ui/pom.xml
By default node-sass will try to download the binding.node binary file
from GitHub, which is of course blocked when offline.
Just setting the relevant environment variable to tell it to always
compile it won't work, because then node-gyp will try to download the
Node.js headers from nodejs.org, which is of course also blocked when
offline.
Passing the dist-url for node-gyp via the `npm_config_dist_url`
environment variable won't work, because node-sass spawns node-gyp in
some way that all the environment of the npm process are not there.
Creating a `node_modules/.hooks/preinstall` script on our end is the
only way to get control over it from our level. We only really want to
do things from this script if it's being run by maven (i.e. in our
Koji instance), and for the node-sass …
> Build the node-sass binary with mvn offline builds

- .circleci/config.yml
- ui/src/components/configuration/ServiceSDKDocs.js
- ui/src/components/configuration/ServiceSDKDocs.test.js
- ui/src/components/configuration/ServiceSDKInfo.js
- ui/src/components/configuration/ServiceSDKInfo.test.js
- ui/src/components/configuration/sdk-config-docs/cordova.js
- ui/src/components/configuration/sdk-config-docs/ionic.js
- ui/src/components/configuration/sdk-config-docs/sdkdocs-test-data.js
https://issues.jboss.org/browse/AEROGEAR-8604
- Added a check to avoid crashing in case of unknown service types
- Added unit tests to verify this specific issue
When bound, the sync service app was expected to be of type `sync` instead of `sync-app` (see [here](https://github.com/aerogearcatalog/sync-app-apb/blob/master/roles/bind-sync-app-apb/tasks/main.yml#L42)).
1. Create a new app in MDC
2. Provision the sync-app into the MDC project
3. Bind the sync-app to the app you created in step 1
4. Open the app details, go to the configuration tab and click on ionic and/or cordova
Without this fix, it will crash. With this fix, an error will be logged into the console.
> Issue AEROGEAR-8604

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/web/serverConfigHandler.go
- ui/node_modules/.hooks/preinstall
- ui/src/components/configuration/ConfigurationView.js
- ui/src/components/configuration/sdk-config-docs/cordova.js
- ui/src/components/configuration/sdk-config-docs/ionic.js
- ui/src/components/configuration/sdk-config-docs/sdkdocs-test-data.js
- ui/src/containers/Header.js
- ui/src/reducers/config.js
https://issues.jboss.org/browse/AEROGEAR-8534
1. run mdc as normal. the docs link should continue to work and point to docs.aerogear.org.
2. set an env var `DOCS_PREFIX=<any http url>` and run mdc again. This time you should see the docs point to the new url.
> fix: make the docs url configurable via env var

- ui/package-lock.json
Here are the commands used to upgrade here:
```
npm rm node-sass-chokidar
npm i --save-exact node-sass-chokidar
npm rm eslint
npm i --save-dev --save-exact eslint
npm rm coveralls
npm rm react-scripts
npm i --save-exact coveralls
npm i --save-exact react-scripts@2.1.8
```
Note also that there's a new major version of react-scripts available.
> ⬆ Upgrade some npm dependencies in ui

- package.json
To enable debugging of the Node.js server.
Added an NPM to start the server with the `--inspect` flag, which enables a process to listen for a debugging client.
For more see [Node.js - Debugging](https://nodejs.org/de/docs/guides/debugging-getting-started/).
Running `npm run debug:server` allows code editor to attach to the server and we can debug the server from the editor.
1. Run `npm run debug:server`
2. The server should start with an extra debugger process. The message below should be output in your console.
```sh
Debugger listening on ws://127.0.0.1:9229/a1d95372-f750-4e53-90a4-92b82dc816a9
```
> build: added a script to enable Node.js debugging

- src/components/build/BuildConfigDetails.test.js
https://issues.jboss.org/browse/AEROGEAR-9324
Added a new test file and achieved 100% coverage for the [`BuildConfigDetails.js`](https://github.com/craicoverflow/mobile-developer-console/blob/56b14ca4f199af2297e24d57b716f2a64b9b6820/src/components/build/BuildConfigDetails.js) component.
There were no tests created for this file.
1. Run `npm run coverage | grep 'BuildConfigDetails.js\|Lines`
2. You should see the coverage of this component is at 100%.
3. Inspect the test file to ensure that the cases are satisfactory.
> Added test cases for BuildConfigDetails component

- src/components/build/BuildInformation.test.js
- src/components/build/__snapshots__/BuildInformation.test.js.snap
https://issues.jboss.org/browse/AEROGEAR-9325
Added a test file for the `BuildInformation` component.
Previously there were none.
1. Run `npm run coverage | grep 'Lines\|BuildInformation.js'`
2. The coverage level should be at 100%.
> test: added tests for BuildInformation component

- .gitignore
https://issues.jboss.org/browse/AEROGEAR-9338
Removed references to obsolete files, extensions and directories.
The `.gitignore` file retained references to files, extensions and directories that no longer exist since the MDC refactor.
N/A
> build(gitignore): removed obsolete values from gitignore

- README.md
By following the steps here, a user gets this error if a new cluster is used to deploy MDC for the first time:
```
Error from server (NotFound): oauthclients.oauth.openshift.io "mobile-developer-console" not found
```
1. Target a new remote OpenShift cluster
2. Follow the steps from [here](https://github.com/aerogear/mobile-developer-console#remote-cluster)
3. Make sure that mdc is deployed successfully and you can log in to MDC as well
> fix: missing oauth client

- src/components/build/BuildSummary.test.js
https://issues.jboss.org/browse/AEROGEAR-9331
Added tests cases for `BuildSummary` component.
There were none.
1. Ensure Coveralls is passing.
2. Run `npm run coverage | grep 'Lines\|BuildSummary'` to run tests locally. Check that coverage is 100%.
> test: added missing tests for BuildSummary component

- src/services/openshift.js
#267 has one failing check on `nom run lint`. This fixes that.
Add an short answer for: Why it was done? (E.g The feature X was deprecated.)
1. Run `npm lint`.
2. You should not get any errors (you will get warnings, but that is okay).
> style(lint): wrapped string to new line to fix linting error

- src/components/build/CreateBuildConfigDialog.js
- src/components/build/CreateBuildConfigDialog.test.js
https://issues.jboss.org/browse/AEROGEAR-9367
- Exported the `CreateBuildConfigDialog` class separately from the Redux connect. This allows the class to be tested in isolation.
- Added unit tests for the `CreateBuildConfigDialog` component.
- Removed unused functions from component.
There were no tests for this file.
1. Run `npm run coverage | grep 'Lines\|CreateBuildConfig'`
2. Tests should pass and coverage should be at 100%.
> test: added tests for CreateBuildConfigDialog

- src/components/build/MobileClientBuildHistoryList.test.js
https://issues.jboss.org/browse/AEROGEAR-9375
- Added unit tests for the `MobileClientBuildHistoryList` component.
There were no tests for this file.
1. Run `npm run coverage | grep 'Lines\|MobileClientBuildHistoryList'`
2. Tests should pass and coverage should be at 100%.
> test: added tests for MobileClientBuildHistoryList component

- src/containers/ClientEditBaseClass.js
- src/services/openshift.js
https://issues.jboss.org/browse/AEROGEAR-9423 
On app creation, the `mobile-services.json` object should contain the following properties:
* clientId
* namespaces
* services (empty) 
1. Run MDC.
2. Create a new app. The `mobile-services.json` should be populate with the following structure:
```json
{
"clientId": "myapp",
"namespace": "mobile-console",
"services": []
}
```
> feat(mobile-services.json): populate status object on app create

- README.md
Added syntax highlighting to all code blocks in README.
README code blocks did not have syntax highlighting which makes it easier to read as a user.
1. Check the README.
2. Do (some) code blocks render with different colours?
> docs(readme): added syntax highlighting to code blocks

- src/actions/apps.test.js
- src/actions/buildConfigs.test.js
https://issues.jboss.org/browse/AEROGEAR-9437
Added tests for `src/actions/buildConfigs.js`.
There were no tests.
Mocked Axios calls with [axios-mock-adapter](https://github.com/ctimmerm/axios-mock-adapter).
1. Run `npm run coverage | grep 'Lines\|buildConfigs.js`.
2. All tests should pass.
> test(actions): added buildConfigs tests

- src/components/overview/MobileClientCardView.js
- src/components/overview/MobileClientCardView.test.js
https://issues.jboss.org/browse/AGMS-233
Updated app were filtered only by original name, not the updated one.
Changed filter function.
Add an short answer for: Why it was done? (E.g The feature X was deprecated.)
1. Open MDC
2. Create new app "app"
3. Edit name of your app - change it to something else
4. Try to use filter to find your app by the new name
5. You should be able to find it with the new name and not the original one
> 🐛 Fix: filtering edited apps

- src/reducers/buildConfig.test.js
- src/reducers/buildConfigs.test.js
- src/reducers/createClientAppDialog.js
- src/reducers/createClientAppDialog.test.js
- src/reducers/errors.js
- src/reducers/errors.test.js
- src/reducers/resource.test.js
- src/reducers/services.js
- src/reducers/services.test.js
- src/reducers/user.test.js
Issue: [AEROGEAR-9349](https://issues.jboss.org/browse/AEROGEAR-9349)
Adding unit tests
-  A couple of bugs has been found and fixed in the `errors` reducers. For details about the fix, see [here](https://github.com/aerogear/mobile-developer-console/commit/e9aae9e0acef7703841083ab89bee8847f0c1e30)
- A bug has been found and fixed into the `services` reducers. To see the fix, look [here](https://github.com/aerogear/mobile-developer-console/pull/269/commits/93a8092bff55e69769457bde947cb32ee1b482f4)
- Because of a bug, in some cases the createClientAppDialog reducer was changing the passed in state instead of change a copy. That has been fixed [here](https://github.com/aerogear/mobile-developer-console/pull/269/commits/5794def430fe27f442ca188599c5136d4eb92316)
> Aerogear 9349

- deploy/mobile-client-crd.yaml
- src/components/overview/MobileClientCardView.js
- src/components/overview/MobileClientCardViewItem.js
- src/containers/ClientEditBaseClass.js
- src/containers/DeleteItemButton.js
- src/models/mobileapps/mobileapp.js
- src/services/openshift.js
https://issues.jboss.org/browse/AEROGEAR-9446
1. Remove the ability to edit an app.
2. Use `metadata.name` instead of `spec.name` for the MDC UI.
3. Fixed a bug where the `status` object will not full create sometimes.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/aerogear/UelPDpo2tww
1. Create an app in MDC.
2. Try to edit the app. You should not be able to.
3. Edit `spec.name` of the app resource in OpenShift.
4. The name change should not affect the display name in MDC.
5. Verify that the status object is populated with `clientId`, `services` (empty array) and `namespace`.
> feat: use metadata.name instead of spec.name

- src/components/overview/MobileClientCardViewItem.js
Closes AEROGEAR-9479
https://issues.jboss.org/browse/AEROGEAR-9479
Added the Mobile Security Service icon to the MobileClient card when the service is bound.
1. Make sure the Mobile Security Service is bound to an app.
2. On the home page the app card should show the security icon when it is bound.
> feat: added MSS icon to card when bound

- server/appServices.js
- server/mobile-services-info.js
- server/server.js
- src/models/mobileservices/mobilesecurityserviceappcr.js
Renamed references of "App Security" to be "Mobile Security".
1. In the list of services for a mobile app, inspect visually that there is a service called "Mobile Security".
> feat: renamed App Security to Mobile Security

- src/components/mobileservices/BindButton.test.js
https://issues.jboss.org/browse/AEROGEAR-9497
Add test to the BindButton component
To increase test coverage   
Add test cases around the BindButton component.
1. run `npm run test` locally
2. run  `npm run coverage | grep 'Lines\|BindButton.js'` to get coverage results
> tests(BindButton):Adding tests

- server/mobile-services-info.js
- src/components/mobileservices/BoundServiceRow.js
- src/components/mobileservices/MobileServiceView.js
- src/models/mobileservices/mobilesecurityserviceappcr.js
- src/models/mobileservices/mobileservice.js
https://issues.jboss.org/browse/AEROGEAR-9475
Show the URL/route to the Mobile Security Service from the bound App Security Service row.
To meet acceptance criteria.
1. Run MDC with MSS enabled:
```sh
OPENSHIFT_HOST=$(minishift ip):8443 NAMESPACE=mobile-console OPENSHIFT_USER_TOKEN=$(oc whoami -t) MSS_NAMESPACE=mobile-console MSS_NAMESPACE=mobile-security-service MSS_APPS_NAMESPACE=mobile-security-service-apps npm run start:server
```
2. Create an app in MDC.
3. Bind App Security to the mobile client.
4. View the App Security bound service row. It should have a link to the MSS with the title **Mobile Security Service URL**.
> feat: display route to Mobile Security Service

- server/mobile-services-info.js
This was done previously but was accidentally changed during a merge conflict.
Ensure that the Mobile Security Service URL does not have any leading slash.
1. Ensure Mobile Security Service is running as a service.
2. Create an app in MDC.
3. Bind the Mobile Security Service. 
4. In the Bound Service row, the Mobile Security Service URL should not have a trailing forward slash
> fix: URL was not formatted

- src/actions/builds.test.js
https://issues.jboss.org/browse/AEROGEAR-9536
Added tests to cover the basic action creators.
1. Run `npm run coverage`
2. Look for `builds.js` under `src/actions`
3. Coverage for this file should be at 66.67%.
I didn't add any tests for the `fetchAndWatchBuilds` function as it is more complicated. We can revisit this towards the end of we have time but it is lower priority.
> test(actions/builds.js): add tests

- src/components/build/create_build_config/Validations.js
- src/components/common/Validation.js
- src/components/common/Validation.test.js
https://issues.jboss.org/browse/AEROGEAR-9539
Added validation around "Create build config" name field.
To reduce the risk of a user getting a 422 response back from the server
This was achieved by adding Regex checking of the "Create build config" name. This uses the same regex expression that checks the apps name on creation. 
1. Enable build tab by setting the ENABLE_BUILD_TAB environment variable to true when running MDC.
2. Open the Build tab and click Create build config.
3. Enter a value that should be invalid in the name field. For example - "hhh!!!!www.".
4. Fill out the rest of the form as normal.
5. You should see a red highlighting around the name field and the Create button should be inactive.
PS.: Add images and/or .gifs to illustrate what was changed if this pull request …
> Aerogear 9539

- server/appServices.js
Removed the hard coded mobile security service namespace value.
There is an environment variable that can be passed at runtime to configure this.
1. Run MDC with MSS enabled:
```sh
OPENSHIFT_HOST=$(minishift ip):8443 NAMESPACE=mobile-console OPENSHIFT_USER_TOKEN=$(oc whoami -t) MSS_NAMESPACE=mobile-security-service MSS_APPS_NAMESPACE=mobile-security-service-apps npm run start:server
```
2. Create an app.
3. Bind the mobile security service to the app.
4. `mobile-services.json` should have the mobile security service configuration.
> fix: remove hard-coded namespace value

- src/services/openshift.test.js
- src/setupTests.js
https://issues.jboss.org/browse/AEROGEAR-9470
Added tests for the `OpenShiftWatchEventListener` service.
1. Run `make test`. All tests should pass.
2. Run `npm run coverage | grep 'Lines\|openshift.js'`. Line coverage should be at 66.7%.
1. Did not add tests for the Websocket functions.
2. Did not add tests for `listWithLabels` function as it is not being used.
> test(services/openshift.js): add tests

- package-lock.json
- server/appServices.js
- server/mobile-services-info.js
- server/server.js
- src/actions/fetch.js
- src/actions/services.js
- src/components/mobileservices/BoundServiceRow.js
- src/components/mobileservices/BoundServiceRow.test.js
- src/models/mobileservices/customresourcefactory.js
- src/models/mobileservices/pushapplicationcr.js
- src/models/mobileservices/pushvariantcr.js
- src/services/crmanagers/GenericResourceManager.js
- src/services/crmanagers/OpenShiftWatchEvents.js
- src/services/crmanagers/OpenshiftResourceManagerFactory.js
- src/services/crmanagers/PushVariantResourceManager.js
- src/services/crmanagers/ResourceManagerFactory.js
- src/services/crmanagers/index.js
- src/services/crmanagers/utils.js
- src/services/openshift.js
https://issues.jboss.org/browse/AEROGEAR-9435
- Added ability to customise the resource management for each of the resource type
- Added the PushVariantCR object
- Added the PushApplicationCR object
- Customised the behaviour of the PushVariantCR Manager so that variants are managed
1. Run the MDC as usual
2. Install the UPS operator in the `mobile-console` namespace
3. Use the UPS operator to create a `UnifiedPush` instance
4. Create an app in MDC
5. Click to the app details
6. Click on mobile services
7. Try to bind and unbind the Push Service. Note that Push Service can be bound 2 times, one for android and one for iOS
There is a bug in the binding window: if you select ios and then try to move back to android, the fields does not gets updated. This will be fixed as part of another …
> UPS Operator integration

- server/server.js
- src/components/mobileservices/BoundServiceRow.js
- src/components/mobileservices/MobileServiceView.js
- src/models/mobileservices/mobilesecurityserviceappcr.js
- src/models/mobileservices/mobileservice.js
https://issues.jboss.org/browse/AEROGEAR-9597
Use an environment variable value to display the route to the Mobile Security Service from a bound service row.
This is what is done in the other services.
1. Run MDC with the following command:
```
MSS_URL=route-mobile-security-service.192.168.42.114.nip.io OPENSHIFT_USER_TOKEN=$(oc whoami -t) npm run start:server
```
2. Ensure that the Mobile Security Service is running. You can use [this script](https://gist.github.com/craicoverflow/dbe3f56188bb7f033926ac4c335be0ac#file-install-mss-sh) to install it on your cluster, or contact me for my cluster credentials.
3. Create an app and bind the Mobile Security Service to it.
4. In the bound service view, you should see the URL.
> refactor(url): use environment variable to display route to MSS

- server/server.js
- src/models/mobileservices/mobileservice.js
Update the format of the service list file to match what is generated by the installer. See https://github.com/integr8ly/installation/pull/748/files#r304318416
* Update the format of the services list and filter them using the `mobile:true` flag
* Remove the redundant `/metrics` endpoint. It is added by the Prometheus middleware automatically
* Fix the OPENSHIFT_HOST url if the protocol is specified as part of the env var 
* Run MDC and everything should still work as expected. 
* Add or remove the protocol value of the OPENSHIFT_HOST env var and it should still work.
* The `/metrics` endpoint should still work.
> update the format of the service list

- server/server.js
`fs.readFile` was never returning, meaning that the `DEFAULT_SERVICES` were getting returned instead.
1. Create a file in `$HOME/generated_secret`.
2. Add the following JSON object to it:
```
{
"version": "master",
"components": [
{
"name": "webapp",
"version": "2.10.5",
"host": "https://tutorial-web-app-webapp.apps.demo27-8353.openshiftworkshop.com"
},
{
"name": "3scale",
"version": "2.5.0.GA",
"host": "https://3scale-admin.apps.demo27-8353.openshiftworkshop.com"
},
{
"name": "apicurito",
"version": "0.2.18.Final",
"host": "https://apicurito-app.apps.demo27-8353.openshiftworkshop.com"
},
{
"name": "codeready",
"version": "1.2.0.GA",
"host": "https://codeready-codeready.apps.demo27-8353.openshiftworkshop.com"
},
{
"name": …
```
> fix: return filestream result as promise

- src/components/mobileservices/BindingPanel.js
- src/models/mobileservices/pushvariantcr.js
https://issues.jboss.org/browse/AEROGEAR-9605
The Mobile Client Type form was not updating to match the chosen type from the dropdown toggle when binding the Push Notification Service.
1. Start to bind the Push Notification service to an app.
2. Toggle the Android/iOS choice a few times. The form below should always update to match the chosen type.
3. Complete the binding.
> fix(form): mobile client type form was not updating

- src/components/mobileservices/UnboundServiceRow.js
https://issues.jboss.org/browse/AEROGEAR-9619
Changed the title in the `UnboundServiceRow` from an anchor tag to plain text.
> improvement(title): change from link to plain title

- src/components/mobileservices/BindingPanel.js
https://issues.jboss.org/browse/AEROGEAR-9618
Validation errors were not been reset of a mobile client type when the mobile client type was been changed.
This seems to be the only work around  for this issue. See [https://github.com/mozilla-services/react-jsonschema-form/issues/486](https://github.com/mozilla-services/react-jsonschema-form/issues/486) for background into the solution.
Add a key to form which when changed creates a new form instance which clears validation errors.
1. Bind a new push notification service
2. Try create binding with blank form to cause validation errors
3. Switch the mobile client type
4. Switch back to previous mobile client type
5. No errors should be shown
> Fix(Binding Form): Fix issue with reseting error message on validation

- server/appServices.js
- server/server.js
https://issues.jboss.org/browse/AEROGEAR-9602
Removed deprecation warnings for [godaddy/kubernetes-client](https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md) library.
1. Run the MDC server: `OPENSHIFT_HOST=$(minishift ip):8443 OPENSHIFT_USER_TOKEN=$(oc whoami -t) npm run start:server`
2. There will now only be 3 deprecation warnings printed in the console on startup:
```sh
kubernetes-client deprecated .getStream see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md server/appServices.js:67:22                  
kubernetes-client deprecated .getStream see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md …
```
> refactor(kubeclient): remove deprecation warnings

- src/components/create_client/EditMobileClientBaseClass.js
https://issues.jboss.org/browse/AEROGEAR-9628
Fix wording in Create App Model
Replace 'Our JavaScript SDK **supports** the following frameworks' with 'Our JavaScript SDK **can be used with** the following frameworks'
1. Create Mobile App in MDC
2. Create Mobile App model should have the text block:
> *Create cross-platform mobile apps using Javascript.
>  You can use the following JavaScript frameworks:*
> Fix: Fix wording in Create App Model

- server/server.js
An undefined variable `kubeclient` was being referenced which does not exist. `kubeconfig` should have been used.
```
oc logs -f example-mdc-1-jbfqd -c mdc
npm info it worked if it ends with ok
npm info using npm@6.9.0
npm info using node@v10.16.0
npm info lifecycle ui@0.1.0~prestart: ui@0.1.0
npm info lifecycle ui@0.1.0~start: ui@0.1.0
> ui@0.1.0 start /opt/app-root/src
> node server/server.js
Failed to init kube client ReferenceError: kubeclient is not defined
at initKubeClient (/opt/app-root/src/server/server.js:181:7)
at run (/opt/app-root/src/server/server.js:224:28)
at Object.<anonymous> (/opt/app-root/src/server/server.js:231:1)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load …
```
> fix: undefined variable

- server/mobile-services.js
- server/server.js
- src/models/mobileservices/mobileservice.js
https://issues.jboss.org/browse/AEROGEAR-9621
Added ability to link to downstream docs for each mobile service. When set this will override the downstream documentation link.
1. Run MDC with all services running in your cluster, with the following environment variables:
* `UPS_DOCUMENTATION_URL=www.google.ie`
* `IDM_DOCUMENTATION_URL=https://en.wikipedia.org`
* `SYNC_DOCUMENTATION_URL=www.bing.com`
* `MSS_DOCUMENTATION_URL=https://www.github.com`.
2. Bind each of the services to an app.
3. In each Bound Service, click the `SDK Setup` link. They should direct you to the URLs defined in step 1.
4. Repeat these steps, except this time exclude some or all of the documentation URL environment variables. The SDK Setup link …
> feat(docs-link): add custom link to downstream service docs

- src/services/crmanagers/PushVariantResourceManager.js
https://issues.jboss.org/browse/AEROGEAR-9654
When logged in as a regular user (evals01), androidvariants and iosvariants failed to load, getting a 403 with the following error message:
"iosvariants.push.aerogear.org is forbidden: User \"evals01\" cannot list iosvariants.push.aerogear.org at the cluster scope: no RBAC policy matched".
This was because the API request for these resources was cluster-scoped.
This pull request changed the request to be look at the same namespace as the parent PushApplication resource.
**To verify**
1. Login to https://mdc-mdc-proxy-mobile-developer-console.apps.mdsdemo-710a.openshiftworkshop.com/ cluster as evals01@example.com / Password1
2. Check the browser developer console. You should not be getting 403 errors on these resources.
> fix: permissions error on AndroidVariant, IOSVariant custom resources

- src/components/mobileservices/validator/rules/MaxLengthRule.js
- src/components/mobileservices/validator/rules/MaxLengthRule.test.js
- src/components/mobileservices/validator/rules/ValidationRule.js
- src/models/mobileservices/keycloakrealmcr.js
https://issues.jboss.org/browse/AGMS-619
* adds field value size limit for the auth realmId field (36)
Keycloak database realm id/name schema has a max size limit of 36 chars.
* Created a new MaxLengthRule validation rule
* RealmId field can now be edited when binding an auth service
* Build an image using this branch and deploy it
* Bind an auth service using a realm id that has a length greater than 36 chars 
* The form should throw an error
* Edit the realm id value and use a value that is small enough
* Form submission should work now.
I have an image available with the mentioned changes: `docker.io/odranoel/mdc:dev`
> maxlength realmId

- src/models/mobileservices/keycloakrealmcr.js
https://issues.jboss.org/browse/AGMS-620
This change removes the ability for the end-user to set the client type when binding an app to Keycloak. Bearer is not a valid type for a mobile app, so instead the type defaults to "public".
2. Bind Identity Management. Notice you will not see the option to set client type any more in the wizard.
3. Once bound, view the custom resource created. For example, here is my app, "myapp-realm".
```sh
$ oc get keycloakrealms myapp-realm -o json | grep 'publicClient'
"publicClient": true,
```
The default value "public" was used to set it to a public client.
> fix: remove ability to set client type in wizard

- src/actions/services.js
- src/components/mobileservices/BindingPanel.js
- src/services/crmanagers/MobileSecurityAppResourceManager.js
- src/services/crmanagers/ResourceManagerFactory.js
https://issues.jboss.org/browse/AGMS-701
This change will prevent multiple apps with the same unique ID getting bound to the Mobile Security Service.
2. Bind Mobile Security with an app ID "com.myapp".
3. Create a second app.
4. Try to bind Mobile Security again with the same app ID.
5. You should get an error message and the binding will be prevented.
> feat(validation): prevent mobile security service binding if app id exists

- src/services/crmanagers/MobileSecurityAppResourceManager.js
https://issues.jboss.org/browse/AGMS-753
Update to validation checks on existing MSS to be case insensitive
Possible issue on iOS and android devices with case sensitive names 
In check for existing MMS id's the id's are convert to lower case and then checked.
1. Create an app in MDC
2. Bind MSS to that app with Unique App Identifier, eg: `com.myapp`
3. Create a second app in MDC
4. Try bind MSS to the second app using an upper-case Unique App Identifier from step 2, eg: `COM.MYAPP`
5. Result: Error message returned saying `App identifier already exists` 
> Fix: MSS binding validation to be case insensitive

- src/models/mobileservices/mobilesecurityserviceappcr.js
https://issues.jboss.org/browse/AEROGEAR-9749
The regular expression was inefficient and was causing the application to freeze with a long app ID.
2. Go to bind Mobile Security.
3. Enter the following string as app ID:  "V0AhG1Tntt19LjszklOgzMeYrJzfffsdfkfddddddddddddddddddddddddddddddddskdkadksdkdff".
4. The following validation message should appear:
_Unique identifier must have at least two segments separated by dots (.). Each segment must start with a letter or a hyphen. Valid characters: [a-zA-Z0-9_-]._
5. Change the app ID to something valid, for example:
"-com.example.myapp"
6. Mobile security should bind successfully.
> fix: application freezes during regular expression check

- src/models/mobileservices/mobilesecurityserviceappcr.js
https://issues.jboss.org/browse/AEROGEAR-9748
Added a maxlength rule on the Mobile Security Service app ID.
2. Click "Bind to App" on Mobile Security.
3. Enter a string > 255 characters.
4. The validation rule. should prevent the binding.
Depends on https://github.com/aerogear/mobile-developer-console/pull/373
> refactor(maxlength): added a max length for app ID

- server/appServices.js
- server/mobile-security-crd.json
- server/mobile-services.js
- server/server.js
https://issues.jboss.org/browse/AGMS-805
Change how the url for MSS is created in the mobile.services.json file.
The use of the config map is been removed from the MSS
Change how the `getServices()` works for MSS resources
1. Create an app
2. Bind the mobile security service to the app
3. With a successfully bind the url should be shown in the mobile-services.json.
> Refactor: MSS url not taken from configmap

- src/components/configuration/sdk-config-docs/cordova.js
- src/components/configuration/sdk-config-docs/ionic.js
https://issues.jboss.org/browse/AEROGEAR-9770
The Mobile Security Service details was add to the condova and ionic configuration files.
When binding a mobile security service to an app the links to the service documentation was not shown 
Update config file
1. Create an app in MDC
2. Bind MSS to the app
3. Under the configuration tab, check Cordova and Ionic both show *Security* in the `Service specific documentation` section
4. Follow the links to external docs. These should point to the AreaGear docs. 
> Fix(Service List): Add missing services to the configuration files for cordova and ionic

- src/components/mobileservices/BindingPanel.js
- src/components/mobileservices/BindingStatus.js
- src/components/mobileservices/BoundServiceRow.js
- src/components/mobileservices/MobileServiceView.js
- src/components/mobileservices/UnboundServiceRow.js
- src/models/mobileservices/customresource.js
- src/models/mobileservices/mobileservice.js
- src/services/crmanagers/PushVariantResourceManager.js
JIRA: https://issues.jboss.org/browse/AEROGEAR-8283 
Modified the `mobileservice.isBindingOperationInProgress` so that it can receive an `owner` parameter. This way we will be able to ask if a binding operation is in progress for a particular application
Modified the BindingPanel to get closed automatically only if the wizard has reached the latest step and the binding was in progress. This is to avoid that another binding for the same app could cause this window to get closed before the latest step has been reached (since `isBindingOperationInProgress(appName)` would return `false` since this operation has not started yet).
The binding panel in MDC gets automatically closed when `isBindingOperation` returns 'false'.
Without this change, any binding operation on any application will cause …
> Fixed issue AEROGEAR-8283

- src/actions/services.js
- src/components/mobileservices/BindingPanel.js
- src/components/mobileservices/BoundServiceRow.js
- src/components/mobileservices/MobileServiceView.js
- src/components/mobileservices/MobileServiceView.test.js
- src/containers/Client.js
- src/models/mobileapps/mobileapp.js
- src/models/mobileservices/customresource.js
- src/models/mobileservices/datasync.js
- src/models/mobileservices/keycloakrealmcr.js
- src/models/mobileservices/mobilesecurityserviceappcr.js
- src/models/mobileservices/mobileservice.js
- src/models/mobileservices/pushvariantcr.js
https://issues.jboss.org/browse/AEROGEAR-9769
This changes the `mobile.aerogear.org` label on the service custom resources to references the mobile client UID instead of the app name. In Kubernetes, labels have a maximum length of 63 characters, so longer app names meant that services couldn't be bound.
2. Bind all services.
3. Unbind all services.
> refactor: use the app UID for the service custom resource label instead of the app name

- src/components/mobileservices/BindingPanel.js
- src/components/mobileservices/BoundServiceRow.js
- src/components/mobileservices/MobileServiceView.js
- src/components/mobileservices/MobileServiceView.test.js
- src/containers/Client.js
- src/models/mobileservices/customresource.js
- src/models/mobileservices/datasync.js
- src/models/mobileservices/keycloakrealmcr.js
- src/models/mobileservices/mobilesecurityserviceappcr.js
- src/models/mobileservices/mobileservice.js
- src/models/mobileservices/pushvariantcr.js
https://issues.jboss.org/browse/AEROGEAR-9779
Follow up to https://github.com/aerogear/mobile-developer-console/pull/386.
This change will make the change introduced in https://github.com/aerogear/mobile-developer-console/pull/386 backwards compatible, by checking the app label for the new value type (app UID) as well as the old value type (app name).
1. Create a new app.
2. Bind all services.
3. The services should show in the correct lists (Bound Services or Unbound Services).
4. Inspect the service CRs. They should no longer have any labels.
> refactor: compare app label value against app name and UID

- src/containers/ErrorMessages.js
- src/containers/ErrorMessages.test.js
https://issues.jboss.org/browse/AEROGEAR-9711
Add response checking for the ErrorMessage component to handle kind of MobileClient CR
To add better messages displayed to the users
In ErrorMessage.js there is checks in place looking for the `response.data.details.kind` of `mobileclients` and `response.data.reason` of `AlreadyExists` is the error type. This should only happen when a new app is been created with an existing name.
1. Create a new app, eg: myapp
2. Try create a new app with the existing app name, myapp
3. Error message shown will display a meaningfully error message
4. Error message should close when X is pressed
> Feat(ErrorMessages): Added better error message around creating new apps that already exist

- src/components/mobileservices/BindButton.js
- src/components/mobileservices/BindingStatus.js
- src/components/mobileservices/BoundServiceRow.js
- src/components/mobileservices/UnboundServiceRow.js
- src/models/mobileservices/mobileservice.js
JIRA: https://issues.jboss.org/browse/AEROGEAR-AEROGEAR-9780
Changed all the methods returning resources status to accept the appName as parameters so that the result can be filtered for resources related to a given app
The binding page was showing binding status according to the status of operation performed on other apps.
1. Go to [my cluster](https://mdc-mdc-proxy-mobile-developer-console.apps.ziccardi-68bb.open.redhat.com) This cluster contains the previous version of MDC (without this fix)
2. Create a new application
3. Click on the application name to enter its details
4. Click to `Mobile Services` tab
5. Try to bind the identity management services. On this cluster the binding to the identity management service will take forever. That makes easy to test the fix.
6. Create a new …
> Changed the bind methods (AEROGEAR-9780)

- package-lock.json
- package.json
https://issues.jboss.org/browse/AGMS-925
Upgrade to react-scripts@3.1.1
Fix possible security issues
1. Remove node_modules
2. Run `npm install`
3. Run `npm run test` & `npm run lint`
4. Manually check site works
- you may be required to remove the package-lock.json file if there is issues running the eslint
> Fix: Upgrade to react-scripts@3.1.1

- src/components/App.js
- src/components/common/CopyToClipboardMultiline.css
- src/components/common/CopyToClipboardMultiline.scss
- src/components/configuration/ConfigurationView.css
- src/components/configuration/ConfigurationView.scss
- src/components/configuration/ServiceSDKInfo.css
- src/components/configuration/ServiceSDKInfo.scss
https://github.com/aerogear/mobile-developer-console/issues/378
Fixed styles after the new patternfly updates
the pf updates didn't account for some of the styles
Add PageSectionVariants to the app.js file and change it to light.
I added screenshots, but you could run this locally and check the background color
I was also seeing this when I ran the code so unset the width:
> fix(pages): update styles

- src/containers/ErrorMessages.js
- src/containers/ErrorMessages.test.js
- src/style/index.css
- src/style/index.scss
Replace Alerts with pf4 components
To replace alerts.
To align with the pf4 migration efforts.
Replace the Toast notification components with alerts.
Create an error by clicking on the "Create a binding" button
> Replace pf alerts

- server/server.js
https://issues.jboss.org/browse/INTLY-3335
Added a process.exit to the server on kubectl client initialization errors.
It happens sometimes after a fresh installation that CRDs are not ready yet when MDC starts, making the server fail the kubectl client initializations: restarting the pod fixes the issue.
Since pods are automatically restarted, exiting will solve the issue.
> Restart the server on kubectl init errors

- package-lock.json
- package.json
- server/appServices.js
Fix issue https://issues.jboss.org/browse/INTLY-3426 and https://issues.jboss.org/browse/AGMS-711. 
The root cause of the problem is that in the current implementation, there will be X number of concurrent calls to `updateAll` function, where `X` is equal to the number of apps. This is why we see that as the number of apps grow, the app will use more memory. The problem is that in `updateAll` function, it doesn't check if the `updating` flag is set to true.  While we could just add that check to fix the issue, there is a corner case won't be covered by this fix: if there is a changed happened while there is `updateAll` is being executed, this update change will be lost and it means there could be a delay for the mdc to show updated content.
So what we want is to make sure at any given …
> fix memory issue when there are many apps

- src/components/mobileservices/BindingPanel.js
Fixed form validation so that there is a blank form on entry, validates after a user inputs data with live validation, and keeps the disabled button until criteria is met for form submission
Initial form:
After incorrect entry:
After correct entry:
> Disable initial form validation until form changed

- src/components/mobileservices/BindingPanel.js
In the push server, if you tried to change the Mobile Client Type (i.e. from Android to iOS), it would throw an error on the page. Added a fix to resolve the issue.
> Fix validation error

- src/components/overview/MobileClientCardViewItem.js
Noticed the delete modal wasn't pulling in the app name correctly so it was asking to delete "undefined": 
Now correctly pulls in app name:
> Fix app delete modal

- src/components/mobileservices/BoundServiceRow.js
Added fix for Binding button that was missing missing in UPS once an Andriod or iOS variant was created.
> Fix for missing binding button.

- server/mobile-services.js
- src/components/mobileservices/BoundServiceRow.test.js
Make the following text changes for the service/server names on the Mobile App page.
- Identity Management = Identity Management Service
- Unified Push Server = Push Notification Service
- Data Sync = Data Sync Server
> Update service names

- src/components/App.css
- src/components/App.js
- src/components/App.scss
- src/components/mobileservices/BoundServiceRow.test.js
Update the Help icon > Documentation menu item.
- Change link from Documentation to "Getting started"
- Update the link URL to this: https://access.redhat.com/documentation/en-us/red_hat_managed_integration/1/html/getting_started_with_mobile_developer_services/index
- Link should open in a new tab/window
> Documentation menu item update
